<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:ram="urn:eu:move:eFTI:data:standard:ReusableAggregateBusinessInformationEntity:34"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:qdt="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
    xmlns:udt="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34"
    targetNamespace="urn:eu:move:eFTI:data:standard:ReusableAggregateBusinessInformationEntity:34"
    elementFormDefault="qualified">
  <xs:import namespace="urn:eu:move:eFTI:data:standard:QualifiedDataType:34" schemaLocation="FTI010n_urn_eu_move_eFTI_data_standard_QualifiedDataType_34.xsd"/>
  <xs:import namespace="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34" schemaLocation="FTI010n_urn_eu_move_eFTI_data_standard_UnqualifiedDataType_34.xsd"/>
  <xs:complexType name="AssociatedTransportEquipmentType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="CategoryCode" type="qdt:TransportEquipmentCategoryCodeType" minOccurs="0"/>
      <xs:element name="GrossWeightMeasure" type="udt:MeasureType" minOccurs="0"/>
      <xs:element name="UsedCapacityCode" type="qdt:TransportEquipmentFullnessCodeType" minOccurs="0"/>
      <xs:element name="SequenceNumeric" type="udt:NumericType" minOccurs="0"/>
      <xs:element name="VerifiedGrossWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="GrossGoodsWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="NetGoodsWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="GrossGoodsVolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="NetGoodsVolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="GoodsItemUnitQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="ReportableQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="StowagePositionID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="WeightVerificationMethodCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="LoadedTransportDangerousGoods" type="ram:TransportDangerousGoodsType" minOccurs="0"/>
      <xs:element name="AffixedLogisticsSeal" type="ram:LogisticsSealType" minOccurs="0"/>
      <xs:element name="WeightVerifierTradeParty" type="ram:TradePartyType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AttachedTransportEquipmentType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="CategoryCode" type="qdt:TransportEquipmentCategoryCodeType" minOccurs="0"/>
      <xs:element name="UnitQuantity" type="udt:QuantityType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AuthoritativeSignatoryPersonType">
    <xs:sequence>
      <xs:element name="Name" type="udt:TextType" minOccurs="0"/>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CalibratedMeasurementType">
    <xs:sequence>
      <xs:element name="ValueMeasure" type="udt:MeasureType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ContactPersonType">
    <xs:sequence>
      <xs:element name="GivenName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="FamilyName" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CreditorFinancialAccountType">
    <xs:sequence>
      <xs:element name="ProprietaryID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CrossBorderRegulatoryProcedureType">
    <xs:sequence>
      <xs:element name="TypeCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="ImportCustomsOfficeSpecifiedLogisticsLocation" type="ram:LogisticsLocationType" minOccurs="0"/>
      <xs:element name="ExportCustomsOfficeSpecifiedLogisticsLocation" type="ram:LogisticsLocationType" minOccurs="0"/>
      <xs:element name="TransitCustomsOfficeSpecifiedLogisticsLocation" type="ram:LogisticsLocationType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentAuthenticationType">
    <xs:sequence>
      <xs:element name="ActualDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="StatementCode" type="udt:CodeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentClauseType">
    <xs:sequence>
      <xs:element name="Content" type="udt:TextType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentContextParameterType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
      <xs:element name="SpecifiedDocumentVersion" type="ram:DocumentVersionType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentVersionType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EFTIIDInformationType">
    <xs:sequence>
      <xs:element name="UniqueIDSetUIL" type="ram:UILType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExchangedDocumentContextType">
    <xs:sequence>
      <xs:element name="MessageStandardSpecifiedDocumentContextParameter" type="ram:DocumentContextParameterType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExchangedDocumentType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
      <xs:element name="TypeCode" type="qdt:DocumentCodeType"/>
      <xs:element name="StatusCode" type="qdt:DocumentStatusCodeType"/>
      <xs:element name="IssueDateTime" type="udt:DateTimeType"/>
      <xs:element name="IncludedNote" type="ram:NoteType" minOccurs="0"/>
      <xs:element name="RequestedSpecifiedQuery" type="ram:SpecifiedQueryType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExemptionCalculationType">
    <xs:sequence>
      <xs:element name="ReportableQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="HazardCategoryCode" type="udt:CodeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GeographicalCoordinateType">
    <xs:sequence>
      <xs:element name="LatitudeMeasure" type="udt:MeasureType"/>
      <xs:element name="LongitudeMeasure" type="udt:MeasureType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsLocationType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="Name" type="udt:TextType" minOccurs="0"/>
      <xs:element name="PhysicalGeographicalCoordinate" type="ram:GeographicalCoordinateType" minOccurs="0"/>
      <xs:element name="PostalTradeAddress" type="ram:TradeAddressType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsPackageType">
    <xs:sequence>
      <xs:element name="ItemQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="TypeCode" type="qdt:PackageTypeCodeType" minOccurs="0"/>
      <xs:element name="Type" type="udt:TextType" minOccurs="0"/>
      <xs:element name="Information" type="udt:TextType" minOccurs="0"/>
      <xs:element name="PhysicalLogisticsShippingMarks" type="ram:LogisticsShippingMarksType" minOccurs="0"/>
      <xs:element name="AssociatedReferencedDocument" type="ram:ReferencedDocumentType" minOccurs="0"/>
      <xs:element name="StatedSpecifiedCondition" type="ram:SpecifiedConditionType" minOccurs="0" maxOccurs="10"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsRiskAnalysisResultType">
    <xs:sequence>
      <xs:element name="ConsignmentRiskRelatedCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="Description" type="udt:TextType" minOccurs="0"/>
      <xs:element name="LevelCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="ScreeningMethodCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="SecurityExemptionCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="Information" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsSealType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="ConditionCode" type="qdt:SealConditionCodeType" minOccurs="0"/>
      <xs:element name="SealingPartyRoleCode" type="qdt:SealingPartyRoleCodeType" minOccurs="0"/>
      <xs:element name="IssuingTradeParty" type="ram:TradePartyType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsServiceChargeType">
    <xs:sequence>
      <xs:element name="ID" type="qdt:FreightChargeTypeIDType" minOccurs="0"/>
      <xs:element name="PaymentArrangementCode" type="qdt:TransportServicePaymentArrangementCodeType" minOccurs="0"/>
      <xs:element name="AppliedAmount" type="udt:AmountType" minOccurs="0"/>
      <xs:element name="PayingPartyRoleCode" type="qdt:ChargePayingPartyRoleCodeType" minOccurs="0"/>
      <xs:element name="CalculationBasisCode" type="qdt:LogisticsChargeCalculationBasisCodeType" minOccurs="0"/>
      <xs:element name="CalculationBasisTradePrice" type="ram:TradePriceType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsShippingMarksType">
    <xs:sequence>
      <xs:element name="Marking" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsTransportEquipmentType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="GrossVolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="CategoryCode" type="qdt:TransportEquipmentCategoryCodeType" minOccurs="0"/>
      <xs:element name="CharacteristicCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="UsedCapacityCode" type="qdt:TransportEquipmentFullnessCodeType" minOccurs="0"/>
      <xs:element name="SequenceNumeric" type="udt:NumericType" minOccurs="0"/>
      <xs:element name="SealQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="StowagePositionID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="GrossGoodsWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="NetGoodsWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="GrossGoodsVolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="NetGoodsVolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="ReportableQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="LoadedTransportDangerousGoods" type="ram:TransportDangerousGoodsType" minOccurs="0" maxOccurs="10"/>
      <xs:element name="AffixedLogisticsSeal" type="ram:LogisticsSealType" minOccurs="0"/>
      <xs:element name="CarriedAssociatedTransportEquipment" type="ram:AssociatedTransportEquipmentType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="OperatingTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="OwnerTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="RegistrationTradeCountry" type="ram:TradeCountryType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsTransportMeansType">
    <xs:sequence>
      <xs:element name="TypeCode" type="qdt:TransportMeansTypeCodeType" minOccurs="0"/>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="Name" type="udt:TextType" minOccurs="0"/>
      <xs:element name="RegistrationTradeCountry" type="ram:TradeCountryType" minOccurs="0"/>
      <xs:element name="OwnerTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="SpecifiedSpatialDimension" type="ram:SpatialDimensionType" minOccurs="0"/>
      <xs:element name="OperationalAttachedTransportEquipment" type="ram:AttachedTransportEquipmentType" minOccurs="0" maxOccurs="10"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LogisticsTransportMovementType">
    <xs:sequence>
      <xs:element name="ModeCode" type="qdt:TransportModeCodeType" minOccurs="0"/>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="SequenceNumeric" type="udt:NumericType" minOccurs="0"/>
      <xs:element name="MasterResponsibleTransportPerson" type="ram:TransportPersonType" minOccurs="0"/>
      <xs:element name="LoadingTransportEvent" type="ram:TransportEventType" minOccurs="0"/>
      <xs:element name="UnloadingTransportEvent" type="ram:TransportEventType" minOccurs="0"/>
      <xs:element name="ArrivalTransportEvent" type="ram:TransportEventType" minOccurs="0"/>
      <xs:element name="DepartureTransportEvent" type="ram:TransportEventType" minOccurs="0"/>
      <xs:element name="UsedLogisticsTransportMeans" type="ram:LogisticsTransportMeansType" minOccurs="0"/>
      <xs:element name="ItineraryTransportRoute" type="ram:TransportRouteType" minOccurs="0"/>
      <xs:element name="CallTransportEvent" type="ram:TransportEventType" minOccurs="0"/>
      <xs:element name="BorderCrossingTransportEvent" type="ram:TransportEventType" minOccurs="0"/>
      <xs:element name="SpecifiedTransportEvent" type="ram:TransportEventType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MeasurementType">
    <xs:sequence>
      <xs:element name="ConditionMeasure" type="udt:MeasureType" minOccurs="0"/>
      <xs:element name="TypeCode" type="udt:CodeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MessageInformationType">
    <xs:sequence>
      <xs:element name="SubsetID" type="udt:IDType" maxOccurs="183"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NoteType">
    <xs:sequence>
      <xs:element name="ContentCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="Content" type="udt:TextType" minOccurs="0"/>
      <xs:element name="SubjectCode" type="udt:CodeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RadioactiveMaterialType">
    <xs:sequence>
      <xs:element name="SpecialFormInformation" type="udt:TextType" minOccurs="0"/>
      <xs:element name="RadioactivePackageTransportIndexCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="FissileCriticalitySafetyIndexNumeric" type="udt:NumericType" minOccurs="0"/>
      <xs:element name="ApplicableSpecifiedRadioactiveIsotope" type="ram:SpecifiedRadioactiveIsotopeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReferencedDocumentType">
    <xs:sequence>
      <xs:element name="URIID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="TypeCode" type="qdt:DocumentCodeType" minOccurs="0"/>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="AttachmentBinaryObject" type="udt:BinaryObjectType" minOccurs="0"/>
      <xs:element name="ReferenceTypeCode" type="qdt:ReferenceCodeType" minOccurs="0"/>
      <xs:element name="FormattedIssueDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="SubtypeCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="IssuerTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="IssueLogisticsLocation" type="ram:LogisticsLocationType" minOccurs="0"/>
      <xs:element name="ContractualDocumentClause" type="ram:DocumentClauseType" minOccurs="0"/>
      <xs:element name="AttachedSpecifiedBinaryFile" type="ram:SpecifiedBinaryFileType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReferencedLogisticsTransportEquipmentType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RegulatoryExemptionType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="TypeCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="ReportableExemptionCalculation" type="ram:ExemptionCalculationType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RepresentativePersonType">
    <xs:sequence>
      <xs:element name="Name" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpatialDimensionType">
    <xs:sequence>
      <xs:element name="Description" type="udt:TextType" minOccurs="0"/>
      <xs:element name="WidthMeasure" type="qdt:LinearUnitMeasureType" minOccurs="0"/>
      <xs:element name="LengthMeasure" type="qdt:LinearUnitMeasureType" minOccurs="0"/>
      <xs:element name="HeightMeasure" type="qdt:LinearUnitMeasureType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedBinaryFileType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="IncludedBinaryObject" type="udt:BinaryObjectType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedConditionType">
    <xs:sequence>
      <xs:element name="SubjectTypeCode" type="qdt:SubjectCodeType" minOccurs="0"/>
      <xs:element name="ValueMeasure" type="udt:MeasureType" minOccurs="0"/>
      <xs:element name="ActionCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="ActionDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="StatementCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="Statement" type="udt:TextType" minOccurs="0"/>
      <xs:element name="SpecifiedCalibratedMeasurement" type="ram:CalibratedMeasurementType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedFuelType">
    <xs:sequence>
      <xs:element name="TypeCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="VolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="WeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="WorkingPressureMeasure" type="qdt:UnitMeasureType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedLicenceType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="TypeCode" type="udt:CodeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedLocationType">
    <xs:sequence>
      <xs:element name="Name" type="udt:TextType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedObservationType">
    <xs:sequence>
      <xs:element name="ApplicableNote" type="ram:NoteType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedPeriodType">
    <xs:sequence>
      <xs:element name="DurationMeasure" type="udt:MeasureType" minOccurs="0"/>
      <xs:element name="StartDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="EndDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="MaximumDurationMeasure" type="qdt:DurationUnitMeasureType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedQueryType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedRadioactiveIsotopeType">
    <xs:sequence>
      <xs:element name="Name" type="udt:TextType" minOccurs="0"/>
      <xs:element name="ActivityLevelMeasure" type="qdt:UnitMeasureType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SupplyChainConsignmentItemType">
    <xs:sequence>
      <xs:element name="GrossVolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="GoodsUnitQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="ApplicableTransportDangerousGoods" type="ram:TransportDangerousGoodsType" minOccurs="0" maxOccurs="10"/>
      <xs:element name="LinearSpatialDimension" type="ram:SpatialDimensionType" minOccurs="0"/>
      <xs:element name="AssociatedReferencedLogisticsTransportEquipment" type="ram:ReferencedLogisticsTransportEquipmentType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SupplyChainConsignmentType">
    <xs:sequence>
      <xs:element name="CarrierAcceptanceDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="GrossWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="NetWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="GrossVolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="CODAmount" type="udt:AmountType" minOccurs="0"/>
      <xs:element name="PackageQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="TransportEquipmentQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="Information" type="udt:TextType" minOccurs="0"/>
      <xs:element name="DeclaredValueForCarriageAmount" type="udt:AmountType" minOccurs="0"/>
      <xs:element name="PaymentArrangementCode" type="qdt:TransportServicePaymentArrangementCodeType" minOccurs="0"/>
      <xs:element name="DeliveryInformation" type="udt:TextType" minOccurs="0"/>
      <xs:element name="CargoInsuranceInstructionsInformation" type="udt:TextType" minOccurs="0"/>
      <xs:element name="TransshipmentPermissionIndicator" type="udt:IndicatorType" minOccurs="0"/>
      <xs:element name="ConsignorProvidedInformation" type="udt:TextType" minOccurs="0"/>
      <xs:element name="ContractTermsInformation" type="udt:TextType" minOccurs="0"/>
      <xs:element name="ConsignorTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="ConsigneeTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="CarrierTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="FreightForwarderTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="ConnectingCarrierTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="CarrierAcceptanceLogisticsLocation" type="ram:LogisticsLocationType" minOccurs="0"/>
      <xs:element name="TransshipmentLogisticsLocation" type="ram:LogisticsLocationType" minOccurs="0"/>
      <xs:element name="ConsigneeReceiptLogisticsLocation" type="ram:LogisticsLocationType" minOccurs="0"/>
      <xs:element name="TransportContractReferencedDocument" type="ram:ReferencedDocumentType" minOccurs="0"/>
      <xs:element name="AssociatedReferencedDocument" type="ram:ReferencedDocumentType" minOccurs="0"/>
      <xs:element name="DeliveryTransportEvent" type="ram:TransportEventType" minOccurs="0"/>
      <xs:element name="TransportEvent" type="ram:TransportEventType" minOccurs="0"/>
      <xs:element name="IncludedSupplyChainConsignmentItem" type="ram:SupplyChainConsignmentItemType" minOccurs="0" maxOccurs="10"/>
      <xs:element name="UtilizedLogisticsTransportEquipment" type="ram:LogisticsTransportEquipmentType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="MainCarriageLogisticsTransportMovement" type="ram:LogisticsTransportMovementType" minOccurs="0" maxOccurs="10"/>
      <xs:element name="PreCarriageLogisticsTransportMovement" type="ram:LogisticsTransportMovementType" minOccurs="0"/>
      <xs:element name="OnCarriageLogisticsTransportMovement" type="ram:LogisticsTransportMovementType" minOccurs="0"/>
      <xs:element name="SpecifiedLogisticsTransportMovement" type="ram:LogisticsTransportMovementType" minOccurs="0"/>
      <xs:element name="TransportService" type="ram:TransportServiceType" minOccurs="0"/>
      <xs:element name="ApplicableLogisticsServiceCharge" type="ram:LogisticsServiceChargeType" minOccurs="0"/>
      <xs:element name="TransportLogisticsPackage" type="ram:LogisticsPackageType" minOccurs="0"/>
      <xs:element name="AssociatedTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="NatureIdentificationTransportCargo" type="ram:TransportCargoType" minOccurs="0"/>
      <xs:element name="ApplicableCrossBorderRegulatoryProcedure" type="ram:CrossBorderRegulatoryProcedureType" minOccurs="0"/>
      <xs:element name="ApplicableTransportDangerousGoods" type="ram:TransportDangerousGoodsType" minOccurs="0"/>
      <xs:element name="ConsignorProvidedBorderClearanceTransportInstructions" type="ram:TransportInstructionsType" minOccurs="0"/>
      <xs:element name="SpecifiedLogisticsRiskAnalysisResult" type="ram:LogisticsRiskAnalysisResultType" minOccurs="0"/>
      <xs:element name="NotifiedTransportationWasteMaterial" type="ram:TransportationWasteMaterialType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TaxRegistrationType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradeAddressType">
    <xs:sequence>
      <xs:element name="PostcodeCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="PostOfficeBox" type="udt:TextType" minOccurs="0"/>
      <xs:element name="StreetName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="CityName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="CountryID" type="qdt:CountryIDType" minOccurs="0"/>
      <xs:element name="CountrySubDivisionName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="BuildingNumber" type="udt:TextType" minOccurs="0"/>
      <xs:element name="DepartmentName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="AdditionalStreetName" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradeContactType">
    <xs:sequence>
      <xs:element name="PersonName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="TelephoneUniversalCommunication" type="ram:UniversalCommunicationType" minOccurs="0"/>
      <xs:element name="FaxUniversalCommunication" type="ram:UniversalCommunicationType" minOccurs="0"/>
      <xs:element name="EmailURIUniversalCommunication" type="ram:UniversalCommunicationType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradeContractType">
    <xs:sequence>
      <xs:element name="IssueDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="SpecifiedDurationMeasure" type="qdt:DurationUnitMeasureType" minOccurs="0"/>
      <xs:element name="SignedSpecifiedLocation" type="ram:SpecifiedLocationType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradeCountryType">
    <xs:sequence>
      <xs:element name="ID" type="qdt:CountryIDType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradePartyType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="Name" type="udt:TextType" minOccurs="0"/>
      <xs:element name="RoleCode" type="qdt:PartyRoleCodeType" minOccurs="0"/>
      <xs:element name="DefinedTradeContact" type="ram:TradeContactType" minOccurs="0"/>
      <xs:element name="PostalTradeAddress" type="ram:TradeAddressType" minOccurs="0"/>
      <xs:element name="SpecifiedTaxRegistration" type="ram:TaxRegistrationType" minOccurs="0"/>
      <xs:element name="SpecifiedRepresentativePerson" type="ram:RepresentativePersonType" minOccurs="0"/>
      <xs:element name="SpecifiedAuthoritativeSignatoryPerson" type="ram:AuthoritativeSignatoryPersonType" minOccurs="0"/>
      <xs:element name="SpecifiedContactPerson" type="ram:ContactPersonType" minOccurs="0"/>
      <xs:element name="OwnedCreditorFinancialAccount" type="ram:CreditorFinancialAccountType" minOccurs="0"/>
      <xs:element name="AgreedTradeContract" type="ram:TradeContractType" minOccurs="0"/>
      <xs:element name="ApplicableSpecifiedLicence" type="ram:SpecifiedLicenceType" minOccurs="0"/>
      <xs:element name="ConfirmedDocumentAuthentication" type="ram:DocumentAuthenticationType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradePriceType">
    <xs:sequence>
      <xs:element name="BasisQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="UnitAmount" type="udt:AmountType" minOccurs="0"/>
      <xs:element name="CategoryTypeCode" type="udt:CodeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransportationWasteMaterialType">
    <xs:sequence>
      <xs:element name="WeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransportCargoType">
    <xs:sequence>
      <xs:element name="TypeCode" type="qdt:CargoCategoryCodeType" minOccurs="0"/>
      <xs:element name="Identification" type="udt:TextType" minOccurs="0"/>
      <xs:element name="OperationalCategoryCode" type="qdt:CargoOperationalCategoryCodeType" minOccurs="0"/>
      <xs:element name="StatisticalClassificationCode" type="qdt:CargoCommodityCategoryCodeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransportDangerousGoodsType">
    <xs:sequence>
      <xs:element name="UNDGIdentificationCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="RegulatoryAuthorityName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="TechnicalName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="Information" type="udt:TextType" minOccurs="0"/>
      <xs:element name="PackagingDangerLevelCode" type="qdt:DangerousGoodsPackagingLevelCodeType" minOccurs="0"/>
      <xs:element name="GrossWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="HazardTypeCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="HazardClassificationID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="GrossVolumeMeasure" type="qdt:VolumeUnitMeasureType" minOccurs="0"/>
      <xs:element name="NetWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="ExplosiveCargoNetWeightMeasure" type="qdt:WeightUnitMeasureType" minOccurs="0"/>
      <xs:element name="ProperShippingName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="SupplementaryInformation" type="udt:TextType" minOccurs="0"/>
      <xs:element name="ReportableQuantity" type="udt:QuantityType" minOccurs="0"/>
      <xs:element name="TunnelRestrictionCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="SpecialProvisionID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="HazardCategoryCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="LimitedQuantityCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="DensityMeasure" type="qdt:UnitMeasureType" minOccurs="0"/>
      <xs:element name="MeltingPointTemperatureMeasure" type="qdt:TemperatureUnitMeasureType" minOccurs="0"/>
      <xs:element name="PreviousCargoInformation" type="udt:TextType" minOccurs="0"/>
      <xs:element name="LabelTypeCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="ControlTemperatureMeasurement" type="ram:MeasurementType" minOccurs="0"/>
      <xs:element name="EmergencyTemperatureMeasurement" type="ram:MeasurementType" minOccurs="0"/>
      <xs:element name="RadioactiveMaterial" type="ram:RadioactiveMaterialType" minOccurs="0"/>
      <xs:element name="SpecifiedLogisticsPackage" type="ram:LogisticsPackageType" minOccurs="0"/>
      <xs:element name="StatedSpecifiedCondition" type="ram:SpecifiedConditionType" minOccurs="0" maxOccurs="10"/>
      <xs:element name="RelatedReferencedDocument" type="ram:ReferencedDocumentType" minOccurs="0"/>
      <xs:element name="IncludedSpecifiedFuel" type="ram:SpecifiedFuelType" minOccurs="0"/>
      <xs:element name="TechnicalNameNote" type="ram:NoteType" minOccurs="0"/>
      <xs:element name="ApplicableRegulatoryExemption" type="ram:RegulatoryExemptionType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransportEventType">
    <xs:sequence>
      <xs:element name="TypeCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="EstimatedOccurrenceDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="ActualOccurrenceDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="ScheduledOccurrenceDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="RequestedOccurrenceDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="OccurrenceLogisticsLocation" type="ram:LogisticsLocationType" minOccurs="0"/>
      <xs:element name="CertifyingTradeParty" type="ram:TradePartyType" minOccurs="0"/>
      <xs:element name="RelatedSpecifiedObservation" type="ram:SpecifiedObservationType" minOccurs="0"/>
      <xs:element name="AdditionalSecurityMeasuresApplicableNote" type="ram:NoteType" minOccurs="0"/>
      <xs:element name="ScheduledOccurrenceSpecifiedPeriod" type="ram:SpecifiedPeriodType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransportInstructionsType">
    <xs:sequence>
      <xs:element name="Description" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransportPersonType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="BirthDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="GivenName" type="udt:TextType" minOccurs="0"/>
      <xs:element name="FamilyName" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransportRouteType">
    <xs:sequence>
      <xs:element name="Description" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransportServiceType">
    <xs:sequence>
      <xs:element name="Description" type="udt:TextType" minOccurs="0"/>
      <xs:element name="ConditionTypeCode" type="qdt:TransportServiceConditionCodeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UILType">
    <xs:sequence>
      <xs:element name="GateID" type="udt:IDType"/>
      <xs:element name="PlatformID" type="udt:IDType"/>
      <xs:element name="DatasetID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UniversalCommunicationType">
    <xs:sequence>
      <xs:element name="URIID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="CompleteNumber" type="udt:TextType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
