<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:udt="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34"
    elementFormDefault="qualified"
    version="34.0">
  <xs:complexType name="CodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="DateTimeDateTimeStringContentType">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:complexType name="DateTimeType">
    <xs:choice>
      <xs:element name="DateTimeString">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="udt:DateTimeDateTimeStringContentType">
              <xs:attribute name="format" type="xs:string" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="IDType">
    <xs:simpleContent>
      <xs:extension base="xs:token">
        <xs:attribute name="schemeID" type="xs:token" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="NumericType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal"/>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>
