SELECT DISTINCT ON (platform_id, dataset_id)
  row_id,
  dataset_id,
  platform_id,
  gate_id,
  xml,
  status::text,
  transport_mode,
  to_json(acceptance_date at time zone 'utc') as acceptance_date,
  acceptance_country,
  to_json(delivery_date at time zone 'utc') as delivery_date,
  delivery_country,
  dangerous_goods,
  main_transport_id,
  main_transport_type,
  transport_reg_country,
  to_json(loading_date at time zone 'utc') as loading_date,
  loading_country,
  to_json(unloading_date at time zone 'utc') as unloading_date,
  unloading_country,
  used_equipment_ids,
  used_equipment_categories,
  used_equipment_countries,
  used_equipment_seq,
  carried_equipment_ids,
  carried_equipment_categories,
  carried_equipment_seq,
  created_by,
  created_at
FROM consignments
ORDER BY platform_id, dataset_id, created_at DESC
LIMIT COALESCE(:limit::int, 20) OFFSET COALESCE(:offset::int, 0);
