INSERT INTO consignments (
  dataset_id,
  platform_id,
  gate_id,
  xml,
  status,
  transport_mode,
  acceptance_date,
  acceptance_country,
  delivery_date,
  delivery_country,
  dangerous_goods,
  main_transport_id,
  main_transport_type,
  transport_reg_country,
  loading_date,
  loading_country,
  unloading_date,
  unloading_country,
  used_equipment_ids,
  used_equipment_categories,
  used_equipment_countries,
  used_equipment_seq,
  carried_equipment_ids,
  carried_equipment_categories,
  carried_equipment_seq,
  created_by
)
SELECT
  dataset_id,
  COALESCE(:platformId, platform_id),
  COALESCE(:gateId, gate_id),
  COALESCE(:xml, xml),
  COALESCE(:status, 'active')::consignment_status,
  COALESCE(:transportMode, transport_mode),
  COALESCE(:acceptanceDate, acceptance_date),
  COALESCE(:acceptanceCountry, acceptance_country),
  COALESCE(:deliveryDate, delivery_date),
  COALESCE(:deliveryCountry, delivery_country),
  COALESCE(:dangerousGoods, dangerous_goods),
  COALESCE(:mainTransportId, main_transport_id),
  COALESCE(:mainTransportType, main_transport_type),
  COALESCE(:transportRegCountry, transport_reg_country),
  COALESCE(:loadingDate, loading_date),
  COALESCE(:loadingCountry, loading_country),
  COALESCE(:unloadingDate, unloading_date),
  COALESCE(:unloadingCountry, unloading_country),
  COALESCE(:usedEquipmentIds, used_equipment_ids),
  COALESCE(:usedEquipmentCategories, used_equipment_categories),
  COALESCE(:usedEquipmentCountries, used_equipment_countries),
  COALESCE(:usedEquipmentSeq, used_equipment_seq),
  COALESCE(:carriedEquipmentIds, carried_equipment_ids),
  COALESCE(:carriedEquipmentCategories, carried_equipment_categories),
  COALESCE(:carriedEquipmentSeq, carried_equipment_seq),
  COALESCE(:createdBy, created_by)
FROM (
  SELECT DISTINCT ON (dataset_id)
    *
  FROM consignments
  WHERE dataset_id = :datasetId
  ORDER BY dataset_id, created_at DESC
) latest
RETURNING
  row_id,
  dataset_id,
  platform_id,
  gate_id,
  xml,
  status::text,
  transport_mode,
  acceptance_date,
  acceptance_country,
  delivery_date,
  delivery_country,
  dangerous_goods,
  main_transport_id,
  main_transport_type,
  transport_reg_country,
  loading_date,
  loading_country,
  unloading_date,
  unloading_country,
  used_equipment_ids,
  used_equipment_categories,
  used_equipment_countries,
  used_equipment_seq,
  carried_equipment_ids,
  carried_equipment_categories,
  carried_equipment_seq,
  created_by,
  created_at;
