services:
  ui:
    build:
      args:
        - VITE_USE_PROD_TARA_URL=false
    networks:
      - default
      - proxy
    labels:
      - caddy=eu-ee.pikker.dev
      - caddy.reverse_proxy={{upstreams 80}}
      - caddy.reverse_proxy.lb_retries=10
      - caddy.reverse_proxy.lb_try_interval=500ms

networks:
  proxy:
    external: true
