# Add more config for localhost development, e.g. port bindings
services:
  database:
    ports:
      - "${EFTI_DB_PORT:-54321}:5432"
  resql:
    ports:
      - "${EFTI_RESQL_PORT:-8090}:8090"
    develop:
      watch:
        - action: sync+restart
          path: ./DSL/Resql
          target: /app/sql
  ruuter:
    ports:
      - "${EFTI_RUUTER_PORT:-8086}:8086"
    healthcheck:
      start_interval: 1s
      interval: 60s
    develop:
      watch:
        - action: sync+restart
          path: ./DSL/Ruuter
          target: /app/DSL
  edelivery:
    ports:
      - 8081:8081
      - 5051:5051
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5051
  xml-mapper:
    ports:
      - 8082:8082
      - 5052:5052
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5052
  multiplexer:
    ports:
      - 8083:8083
      - 5053:5053
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5053
  ui:
    ports:
      - 8000:80
    build:
      args:
        - VITE_USE_PROD_TARA_URL=false

  tara-mock:
    ports:
      - "8888:8080"

  tim:
    ports:
      - "8085:8085"

  tim-database:
    ports:
      - "19433:5432"

  http-tests:
    image: jetbrains/intellij-http-client
    depends_on:
      - ruuter
      - xml-mapper
    volumes:
      - ./:/workdir
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - "java -cp '/intellij-http-client/*' com.intellij.httpClient.cli.HttpClientMain -L VERBOSE --env-file tests/http-client.env.json -e docker --no-progress ${TEST_FILES:-tests/*/*.http}"
