<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:qdt="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
           elementFormDefault="qualified"
           version="34.0">
  <xs:import namespace="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34" schemaLocation="eFTIXMn_urn_eu_move_eFTI_data_standard_UnqualifiedDataType_34.xsd"/>
  <xs:simpleType name="CargoCategoryCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="CargoCategoryCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:CargoCategoryCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CargoCommodityCategoryCodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token">
        <xs:attribute name="listAgencyID" type="xs:token" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="CargoOperationalCategoryCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="CargoOperationalCategoryCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:CargoOperationalCategoryCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="ChargePayingPartyRoleCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="ChargePayingPartyRoleCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:ChargePayingPartyRoleCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="CountryIDContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="CountryIDType">
    <xs:simpleContent>
      <xs:extension base="qdt:CountryIDContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="DangerousGoodsPackagingLevelCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="DangerousGoodsPackagingLevelCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:DangerousGoodsPackagingLevelCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DocumentCodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DocumentStatusCodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DurationUnitMeasureType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="unitCode" type="qdt:DurationUnitMeasureUnitCodeContentType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="DurationUnitMeasureUnitCodeContentType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FreightChargeTypeIDContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="FreightChargeTypeIDType">
    <xs:simpleContent>
      <xs:extension base="qdt:FreightChargeTypeIDContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="LinearUnitMeasureType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="unitCode" type="qdt:LinearUnitMeasureUnitCodeContentType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="LinearUnitMeasureUnitCodeContentType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="LogisticsChargeCalculationBasisCodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token">
        <xs:attribute name="listAgencyID" type="xs:token" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PackageTypeCodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="PartyRoleCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="PartyRoleCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:PartyRoleCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="ReferenceCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="ReferenceCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:ReferenceCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="SealConditionCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="SealConditionCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:SealConditionCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="SealingPartyRoleCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="SealingPartyRoleCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:SealingPartyRoleCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SubjectCodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TemperatureUnitMeasureType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="unitCode" type="qdt:TemperatureUnitMeasureUnitCodeContentType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="TemperatureUnitMeasureUnitCodeContentType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TransportEquipmentCategoryCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:simpleType name="TransportEquipmentCategoryCodeListAgencyIDContentType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="TransportEquipmentCategoryCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportEquipmentCategoryCodeContentType">
        <xs:attribute name="listAgencyID" type="qdt:TransportEquipmentCategoryCodeListAgencyIDContentType" fixed="6" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="TransportEquipmentFullnessCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="TransportEquipmentFullnessCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportEquipmentFullnessCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="TransportMeansTypeCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="TransportMeansTypeCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportMeansTypeCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="TransportModeCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="TransportModeCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportModeCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="TransportServiceConditionCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:simpleType name="TransportServiceConditionCodeListAgencyIDContentType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="TransportServiceConditionCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportServiceConditionCodeContentType">
        <xs:attribute name="listAgencyID" type="qdt:TransportServiceConditionCodeListAgencyIDContentType" fixed="6" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="TransportServicePaymentArrangementCodeContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:simpleType name="TransportServicePaymentArrangementCodeListAgencyIDContentType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="TransportServicePaymentArrangementCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportServicePaymentArrangementCodeContentType">
        <xs:attribute name="listAgencyID" type="qdt:TransportServicePaymentArrangementCodeListAgencyIDContentType" fixed="6" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="UnitMeasureType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="unitCode" type="xs:token" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VolumeUnitMeasureType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="unitCode" type="qdt:VolumeUnitMeasureUnitCodeContentType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="VolumeUnitMeasureUnitCodeContentType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="WeightUnitMeasureType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="unitCode" type="qdt:WeightUnitMeasureUnitCodeContentType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="WeightUnitMeasureUnitCodeContentType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
