@ruuterUrl=http://localhost:8086/efti/api/v1
@resqlUrl=http://localhost:8090/efti

### Platform uploads a new consignment over REST (TODO: auth)
POST {{ruuterUrl}}/consignments
Content-Type: text/xml

< ../../code/xml-mapper/xsd/Normalized/FTI004/sample.xml

> {%
  client.test("Consignment saved", () => {
    client.assert(response.status === 201)
    client.assert(response.body.gateId === "POC")
    client.assert(response.body.platformId === "demo")
    client.assert(response.body.datasetId === "550e8400-e29b-41d4-a716-446655440000")
  })
%}

### Find consignment
POST {{ruuterUrl}}/consignments/search
Content-Type: application/json

{
  "criteria": {
    "mainTransportId": {"operator": "EQ", "id": "VESSEL-001"},
    "transportMode": {"operator": "EQ", "mode": "1"},
    "carriedEquipmentIds": {"operator": "EQ", "id": "TE-004"},
    "deliveryCountry": {"operator": "EQ", "country": "EE"},
    "deliveryDate": [{"operator": "GT", "date": "2025-06-01"}]
  },
  "limit": 10, "offset": 0
}

> {%
  client.test("Find consignment", () => {
    client.assert(response.status === 200)
    client.assert(response.body.length === 1)
    client.assert(response.body[0].datasetId === "550e8400-e29b-41d4-a716-446655440000")
  })
%}

### GET consignments list from Ruuter
GET {{ruuterUrl}}/consignments
Content-Type: application/json

> {%
  client.test("Find consignment", () => {
    client.assert(response.status === 200)
    client.assert(response.body.length === 1)
    client.assert(response.body[0].datasetId === "550e8400-e29b-41d4-a716-446655440000")
  })
%}


### Delete consignment
POST {{resqlUrl}}/soft_delete_consignment
Content-Type: application/json

{"datasetId": "550e8400-e29b-41d4-a716-446655440000"}

> {%
  client.test("Find consignment", () => {
    client.assert(response.status === 200)
    client.assert(response.body[0].datasetId === "550e8400-e29b-41d4-a716-446655440000")
    client.assert(response.body[0].status === "DELETED")
  })
%}
