@ruuterUrl=http://localhost:8086/efti/api/v1
@resqlUrl=http://localhost:8090/efti

### Platform uploads a new consignment over REST (TODO: auth)

POST {{ruuterUrl}}/consignments
Content-Type: text/xml

< ../../code/xml-mapper/xsd/Normalized/FTI004/sample.xml

### Find consignments

POST {{resqlUrl}}/find_consignments
Content-Type: application/json

{
  "criteria": {
    "mainTransportId": {"operator": "EQ", "id": "VESSEL-001"},
    "transportMode": {"operator": "EQ", "mode": "1"},
    "carriedEquipmentIds": {"operator": "EQ", "id": "TE-004"},
    "deliveryCountry": {"operator": "EQ", "country": "EE"},
    "deliveryDate": [{"operator": "GT", "date": "2025-06-01"}]
  },
  "limit": 10, "offset": 0
}
