@baseUrl=http://localhost:8080/api/v1

POST {{baseUrl}}/dataset/request-to-xml
Content-Type: application/json

{
  "uil": {
    "datasetId": "0a1e95cb-b03b-44c8-881d-13c7bfe38c4d",
    "platformId": "demo",
    "gateId": "poc"
  },
  "subsets": ["EE01", "EE02"]
}

###

POST {{baseUrl}}/dataset/request-to-json
Content-Type: text/xml

< xsd/Normalized/FTI009/sample.xml

###

POST {{baseUrl}}/dataset/response-to-json
Content-Type: text/xml

< xsd/Normalized/FTI010/sample.xml
