<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:ram="urn:eu:move:eFTI:data:standard:ReusableAggregateBusinessInformationEntity:34"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:qdt="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
    xmlns:udt="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34"
    targetNamespace="urn:eu:move:eFTI:data:standard:ReusableAggregateBusinessInformationEntity:34"
    elementFormDefault="qualified">
  <xs:import namespace="urn:eu:move:eFTI:data:standard:QualifiedDataType:34" schemaLocation="FTI004n_urn_eu_move_eFTI_data_standard_QualifiedDataType_34.xsd"/>
  <xs:import namespace="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34" schemaLocation="FTI004n_urn_eu_move_eFTI_data_standard_UnqualifiedDataType_34.xsd"/>
  <xs:complexType name="DocumentContextParameterType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
      <xs:element name="SpecifiedDocumentVersion" type="ram:DocumentVersionType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentVersionType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EFTIIDInformationType">
    <xs:sequence>
      <xs:element name="UniqueIDSetUIL" type="ram:UILType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExchangedDocumentContextType">
    <xs:sequence>
      <xs:element name="MessageStandardSpecifiedDocumentContextParameter" type="ram:DocumentContextParameterType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExchangedDocumentType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
      <xs:element name="TypeCode" type="qdt:DocumentCodeType"/>
      <xs:element name="IssueDateTime" type="udt:DateTimeType"/>
      <xs:element name="RequestedSpecifiedQuery" type="ram:SpecifiedQueryType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IDSetCriteriaType">
    <xs:sequence>
      <xs:element name="CarrierAcceptanceDateParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="CarrierAcceptanceCountryParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="DeliveryDateParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="DeliveryCountryParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="DangerousGoodsIndicationCodeParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="MainCarriageTransportMeansIDParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="MainCarriageModeCodeParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="MainCarriageTransportMeansTypeCodeParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="TransportMeansRegistrationCountryParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="MainCarriageLoadingDateParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="MainCarriageLoadingCountryParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="MainCarriageUnloadingDateParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="MainCarriageUnloadingCountryParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="UsedTransportEquipmentIDParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="UsedTransportEquipmentCategoryCodeParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="UsedTransportEquipmentRegistrationCountryParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="UsedTransportEquipmentSequenceNumberParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="CarriedTransportEquipmentIDParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="CarriedTransportEquipmentCategoryCodeParameterScope" type="ram:ScopeType" minOccurs="0"/>
      <xs:element name="CarriedTransportEquipmentSequenceNumberParameterScope" type="ram:ScopeType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ScopeType">
    <xs:sequence>
      <xs:element name="CountryID" type="qdt:CountryIDType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="ID" type="udt:IDType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="SpecifiedDateTime" type="udt:DateTimeType" minOccurs="0"/>
      <xs:element name="DangerousGoodsIndicationParameterCode" type="udt:CodeType" minOccurs="0"/>
      <xs:element name="TransportModeParameterCode" type="qdt:TransportModeCodeType" minOccurs="0"/>
      <xs:element name="TransportMeansParameterCode" type="qdt:TransportMeansTypeCodeType" minOccurs="0"/>
      <xs:element name="TransportEquipmentCategoryParameterCode" type="qdt:TransportEquipmentCategoryCodeType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="SequenceNumeric" type="udt:NumericType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedQueryType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UILType">
    <xs:sequence>
      <xs:element name="GateID" type="udt:IDType"/>
      <xs:element name="PlatformID" type="udt:IDType"/>
      <xs:element name="DatasetID" type="udt:IDType"/>
      <xs:element name="ParameterIDSetCriteria" type="ram:IDSetCriteriaType"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
