<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:ram="urn:eu:move:eFTI:data:standard:ReusableAggregateBusinessInformationEntity:34"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:qdt="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
    xmlns:udt="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34"
    targetNamespace="urn:eu:move:eFTI:data:standard:ReusableAggregateBusinessInformationEntity:34"
    elementFormDefault="qualified">
  <xs:import namespace="urn:eu:move:eFTI:data:standard:QualifiedDataType:34" schemaLocation="FTI025n_urn_eu_move_eFTI_data_standard_QualifiedDataType_34.xsd"/>
  <xs:import namespace="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34" schemaLocation="FTI025n_urn_eu_move_eFTI_data_standard_UnqualifiedDataType_34.xsd"/>
  <xs:complexType name="DocumentContextParameterType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
      <xs:element name="SpecifiedDocumentVersion" type="ram:DocumentVersionType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentVersionType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EFTIIDInformationType">
    <xs:sequence>
      <xs:element name="UniqueIDSetUIL" type="ram:UILType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExchangedDocumentContextType">
    <xs:sequence>
      <xs:element name="MessageStandardSpecifiedDocumentContextParameter" type="ram:DocumentContextParameterType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExchangedDocumentType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
      <xs:element name="TypeCode" type="qdt:DocumentCodeType"/>
      <xs:element name="IssueDateTime" type="udt:DateTimeType"/>
      <xs:element name="Disposition" type="udt:TextType"/>
      <xs:element name="RequestedSpecifiedQuery" type="ram:SpecifiedQueryType"/>
      <xs:element name="RequesterTradeParty" type="ram:TradePartyType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MessageInformationType">
    <xs:sequence>
      <xs:element name="FollowUp" type="udt:TextType" minOccurs="0"/>
      <xs:element name="AttachedSpecifiedBinaryFile" type="ram:SpecifiedBinaryFileType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedBinaryFileType">
    <xs:sequence>
      <xs:element name="FileName" type="udt:TextType"/>
      <xs:element name="MIMECode" type="udt:CodeType"/>
      <xs:element name="EncodingCode" type="udt:CodeType"/>
      <xs:element name="CharacterSetCode" type="udt:CodeType"/>
      <xs:element name="IncludedBinaryObject" type="udt:BinaryObjectType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SpecifiedQueryType">
    <xs:sequence>
      <xs:element name="ID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradeAddressType">
    <xs:sequence>
      <xs:element name="CountryID" type="qdt:CountryIDType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradePartyType">
    <xs:sequence>
      <xs:element name="PostalTradeAddress" type="ram:TradeAddressType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UILType">
    <xs:sequence>
      <xs:element name="GateID" type="udt:IDType"/>
      <xs:element name="PlatformID" type="udt:IDType"/>
      <xs:element name="DatasetID" type="udt:IDType"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
