url: jdbc:postgresql://database:5432/efti
username: efti
password: 01234
searchPath: /liquibase/changelog
changeLogFile: db.changelog-master.yaml
liquibase-schema-name: public
liquibase.hub.mode: off
