<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:rsm="urn:eu:move:eFTI:data:draft:eFTIXM:1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ram="urn:eu:move:eFTI:data:standard:ReusableAggregateBusinessInformationEntity:34"
           targetNamespace="urn:eu:move:eFTI:data:draft:eFTIXM:1"
           elementFormDefault="qualified">
  <xs:import namespace="urn:eu:move:eFTI:data:standard:QualifiedDataType:34" schemaLocation="eFTIXMa_urn_eu_move_eFTI_data_standard_QualifiedDataType_34.xsd"/>
  <xs:import namespace="urn:eu:move:eFTI:data:standard:ReusableAggregateBusinessInformationEntity:34" schemaLocation="eFTIXMa_urn_eu_move_eFTI_data_standard_ReusableAggregateBusinessInformationEntity_34.xsd"/>
  <xs:import namespace="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34" schemaLocation="eFTIXMa_urn_eu_move_eFTI_data_standard_UnqualifiedDataType_34.xsd"/>
  <xs:element name="eFTIXM" type="rsm:eFTIXMType"/>
  <xs:complexType name="eFTIXMType">
    <xs:annotation>
      <xs:documentation>
        <eFTI_BN>eFTI message content</eFTI_BN>
        <eFTI_DEF>eFTI message content.</eFTI_DEF>
        <eFTI_ID>ASBIE1026</eFTI_ID>
        <eFTI_subset>EU01</eFTI_subset>
        <eFTI_subset>EU02</eFTI_subset>
        <eFTI_subset>EU03</eFTI_subset>
        <eFTI_subset>EU05a</eFTI_subset>
        <eFTI_subset>EU05b</eFTI_subset>
        <eFTI_subset>EU05c</eFTI_subset>
        <eFTI_subset>EU06</eFTI_subset>
        <eFTI_subset>AT01</eFTI_subset>
        <eFTI_subset>AT02</eFTI_subset>
        <eFTI_subset>AT03</eFTI_subset>
        <eFTI_subset>AT04</eFTI_subset>
        <eFTI_subset>AT05</eFTI_subset>
        <eFTI_subset>AT06</eFTI_subset>
        <eFTI_subset>AT07</eFTI_subset>
        <eFTI_subset>AT08</eFTI_subset>
        <eFTI_subset>AT09</eFTI_subset>
        <eFTI_subset>AT11</eFTI_subset>
        <eFTI_subset>AT12</eFTI_subset>
        <eFTI_subset>AT13</eFTI_subset>
        <eFTI_subset>AT14</eFTI_subset>
        <eFTI_subset>AT15</eFTI_subset>
        <eFTI_subset>AT16</eFTI_subset>
        <eFTI_subset>BE01</eFTI_subset>
        <eFTI_subset>BE02</eFTI_subset>
        <eFTI_subset>BE03a</eFTI_subset>
        <eFTI_subset>BE03b</eFTI_subset>
        <eFTI_subset>BE04</eFTI_subset>
        <eFTI_subset>BE05</eFTI_subset>
        <eFTI_subset>BE06</eFTI_subset>
        <eFTI_subset>BE07</eFTI_subset>
        <eFTI_subset>BE08</eFTI_subset>
        <eFTI_subset>BE09</eFTI_subset>
        <eFTI_subset>BE10</eFTI_subset>
        <eFTI_subset>BG01</eFTI_subset>
        <eFTI_subset>BG02</eFTI_subset>
        <eFTI_subset>BG03</eFTI_subset>
        <eFTI_subset>BG04</eFTI_subset>
        <eFTI_subset>BG05</eFTI_subset>
        <eFTI_subset>BG06</eFTI_subset>
        <eFTI_subset>BG07</eFTI_subset>
        <eFTI_subset>BG08</eFTI_subset>
        <eFTI_subset>BG09</eFTI_subset>
        <eFTI_subset>BG10a</eFTI_subset>
        <eFTI_subset>BG10b</eFTI_subset>
        <eFTI_subset>CY01</eFTI_subset>
        <eFTI_subset>CY02</eFTI_subset>
        <eFTI_subset>CY03</eFTI_subset>
        <eFTI_subset>CZ01</eFTI_subset>
        <eFTI_subset>CZ02</eFTI_subset>
        <eFTI_subset>CZ03</eFTI_subset>
        <eFTI_subset>CZ04</eFTI_subset>
        <eFTI_subset>CZ05</eFTI_subset>
        <eFTI_subset>DE01</eFTI_subset>
        <eFTI_subset>DE02</eFTI_subset>
        <eFTI_subset>DE03a</eFTI_subset>
        <eFTI_subset>DE03b</eFTI_subset>
        <eFTI_subset>DE03c</eFTI_subset>
        <eFTI_subset>DE04</eFTI_subset>
        <eFTI_subset>DK01</eFTI_subset>
        <eFTI_subset>DK02</eFTI_subset>
        <eFTI_subset>DK03</eFTI_subset>
        <eFTI_subset>DK04</eFTI_subset>
        <eFTI_subset>DK05</eFTI_subset>
        <eFTI_subset>DK06</eFTI_subset>
        <eFTI_subset>EE01</eFTI_subset>
        <eFTI_subset>EE02</eFTI_subset>
        <eFTI_subset>EE04</eFTI_subset>
        <eFTI_subset>EE05a</eFTI_subset>
        <eFTI_subset>EE05b</eFTI_subset>
        <eFTI_subset>EE05c</eFTI_subset>
        <eFTI_subset>EE05d</eFTI_subset>
        <eFTI_subset>EL01</eFTI_subset>
        <eFTI_subset>EL02</eFTI_subset>
        <eFTI_subset>EL03</eFTI_subset>
        <eFTI_subset>EL04</eFTI_subset>
        <eFTI_subset>EL05</eFTI_subset>
        <eFTI_subset>EL07</eFTI_subset>
        <eFTI_subset>EL08</eFTI_subset>
        <eFTI_subset>ES01</eFTI_subset>
        <eFTI_subset>ES02</eFTI_subset>
        <eFTI_subset>ES03</eFTI_subset>
        <eFTI_subset>ES04</eFTI_subset>
        <eFTI_subset>ES05</eFTI_subset>
        <eFTI_subset>FI01</eFTI_subset>
        <eFTI_subset>FI02</eFTI_subset>
        <eFTI_subset>FI03</eFTI_subset>
        <eFTI_subset>FI04</eFTI_subset>
        <eFTI_subset>FR01a</eFTI_subset>
        <eFTI_subset>FR01b</eFTI_subset>
        <eFTI_subset>FR02a</eFTI_subset>
        <eFTI_subset>FR02b</eFTI_subset>
        <eFTI_subset>FR02c</eFTI_subset>
        <eFTI_subset>FR03</eFTI_subset>
        <eFTI_subset>FR04</eFTI_subset>
        <eFTI_subset>FR05</eFTI_subset>
        <eFTI_subset>HR01</eFTI_subset>
        <eFTI_subset>HR03</eFTI_subset>
        <eFTI_subset>HR04</eFTI_subset>
        <eFTI_subset>HR05a</eFTI_subset>
        <eFTI_subset>HR05b</eFTI_subset>
        <eFTI_subset>HR05c</eFTI_subset>
        <eFTI_subset>HU01</eFTI_subset>
        <eFTI_subset>HU02</eFTI_subset>
        <eFTI_subset>HU03</eFTI_subset>
        <eFTI_subset>HU04</eFTI_subset>
        <eFTI_subset>HU05</eFTI_subset>
        <eFTI_subset>HU06</eFTI_subset>
        <eFTI_subset>HU07</eFTI_subset>
        <eFTI_subset>IE01</eFTI_subset>
        <eFTI_subset>IE02</eFTI_subset>
        <eFTI_subset>IE03</eFTI_subset>
        <eFTI_subset>IE05</eFTI_subset>
        <eFTI_subset>IE06</eFTI_subset>
        <eFTI_subset>IE07</eFTI_subset>
        <eFTI_subset>IT01</eFTI_subset>
        <eFTI_subset>IT02</eFTI_subset>
        <eFTI_subset>IT03a</eFTI_subset>
        <eFTI_subset>IT03b</eFTI_subset>
        <eFTI_subset>IT03c</eFTI_subset>
        <eFTI_subset>LT01</eFTI_subset>
        <eFTI_subset>LT02</eFTI_subset>
        <eFTI_subset>LT03a</eFTI_subset>
        <eFTI_subset>LT03b</eFTI_subset>
        <eFTI_subset>LT04</eFTI_subset>
        <eFTI_subset>LT06</eFTI_subset>
        <eFTI_subset>LU01</eFTI_subset>
        <eFTI_subset>LU02</eFTI_subset>
        <eFTI_subset>LU03</eFTI_subset>
        <eFTI_subset>LU04</eFTI_subset>
        <eFTI_subset>LU05</eFTI_subset>
        <eFTI_subset>LU06</eFTI_subset>
        <eFTI_subset>LU07</eFTI_subset>
        <eFTI_subset>LV01</eFTI_subset>
        <eFTI_subset>LV02</eFTI_subset>
        <eFTI_subset>LV03</eFTI_subset>
        <eFTI_subset>LV04</eFTI_subset>
        <eFTI_subset>LV05</eFTI_subset>
        <eFTI_subset>MT01a</eFTI_subset>
        <eFTI_subset>MT01b</eFTI_subset>
        <eFTI_subset>MT02</eFTI_subset>
        <eFTI_subset>NL01</eFTI_subset>
        <eFTI_subset>NL02</eFTI_subset>
        <eFTI_subset>NL03a</eFTI_subset>
        <eFTI_subset>NL03b</eFTI_subset>
        <eFTI_subset>NL04</eFTI_subset>
        <eFTI_subset>NL05</eFTI_subset>
        <eFTI_subset>NL06</eFTI_subset>
        <eFTI_subset>PL01a</eFTI_subset>
        <eFTI_subset>PL01b</eFTI_subset>
        <eFTI_subset>PL01c</eFTI_subset>
        <eFTI_subset>PL02</eFTI_subset>
        <eFTI_subset>PL03</eFTI_subset>
        <eFTI_subset>PL04a</eFTI_subset>
        <eFTI_subset>PL04b</eFTI_subset>
        <eFTI_subset>PL04c</eFTI_subset>
        <eFTI_subset>PL06</eFTI_subset>
        <eFTI_subset>PT01</eFTI_subset>
        <eFTI_subset>PT02</eFTI_subset>
        <eFTI_subset>RO01</eFTI_subset>
        <eFTI_subset>RO02a</eFTI_subset>
        <eFTI_subset>RO02b</eFTI_subset>
        <eFTI_subset>RO03</eFTI_subset>
        <eFTI_subset>RO04</eFTI_subset>
        <eFTI_subset>RO05a</eFTI_subset>
        <eFTI_subset>RO05b</eFTI_subset>
        <eFTI_subset>RO05c</eFTI_subset>
        <eFTI_subset>RO06</eFTI_subset>
        <eFTI_subset>SE01</eFTI_subset>
        <eFTI_subset>SE02</eFTI_subset>
        <eFTI_subset>SE03</eFTI_subset>
        <eFTI_subset>SE04</eFTI_subset>
        <eFTI_subset>SE05</eFTI_subset>
        <eFTI_subset>SE06</eFTI_subset>
        <eFTI_subset>SI01</eFTI_subset>
        <eFTI_subset>SI02</eFTI_subset>
        <eFTI_subset>SI03</eFTI_subset>
        <eFTI_subset>SI05</eFTI_subset>
        <eFTI_subset>SI06</eFTI_subset>
        <eFTI_subset>SK01</eFTI_subset>
        <eFTI_subset>SK02</eFTI_subset>
        <eFTI_subset>SK03</eFTI_subset>
        <eFTI_subset>SK04</eFTI_subset>
        <eFTI_subset>SK05</eFTI_subset>
        <eFTI_xpath>/eFTIXM</eFTI_xpath>
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="ExchangedDocumentContext" type="ram:ExchangedDocumentContextType">
        <xs:annotation>
          <xs:documentation>
            <eFTI_BN>eFTI Message Context</eFTI_BN>
            <eFTI_ID>ASBIE2130</eFTI_ID>
            <eFTI_DEF>The eFTI Regulation context for this eFTI message.</eFTI_DEF>
            <eFTI_subset>EU01</eFTI_subset>
            <eFTI_subset>EU02</eFTI_subset>
            <eFTI_subset>EU03</eFTI_subset>
            <eFTI_subset>EU05a</eFTI_subset>
            <eFTI_subset>EU05b</eFTI_subset>
            <eFTI_subset>EU05c</eFTI_subset>
            <eFTI_subset>EU06</eFTI_subset>
            <eFTI_subset>AT01</eFTI_subset>
            <eFTI_subset>AT02</eFTI_subset>
            <eFTI_subset>AT03</eFTI_subset>
            <eFTI_subset>AT04</eFTI_subset>
            <eFTI_subset>AT05</eFTI_subset>
            <eFTI_subset>AT06</eFTI_subset>
            <eFTI_subset>AT07</eFTI_subset>
            <eFTI_subset>AT08</eFTI_subset>
            <eFTI_subset>AT09</eFTI_subset>
            <eFTI_subset>AT11</eFTI_subset>
            <eFTI_subset>AT12</eFTI_subset>
            <eFTI_subset>AT13</eFTI_subset>
            <eFTI_subset>AT14</eFTI_subset>
            <eFTI_subset>AT15</eFTI_subset>
            <eFTI_subset>AT16</eFTI_subset>
            <eFTI_subset>BE01</eFTI_subset>
            <eFTI_subset>BE02</eFTI_subset>
            <eFTI_subset>BE03a</eFTI_subset>
            <eFTI_subset>BE03b</eFTI_subset>
            <eFTI_subset>BE04</eFTI_subset>
            <eFTI_subset>BE05</eFTI_subset>
            <eFTI_subset>BE06</eFTI_subset>
            <eFTI_subset>BE07</eFTI_subset>
            <eFTI_subset>BE08</eFTI_subset>
            <eFTI_subset>BE09</eFTI_subset>
            <eFTI_subset>BE10</eFTI_subset>
            <eFTI_subset>BG01</eFTI_subset>
            <eFTI_subset>BG02</eFTI_subset>
            <eFTI_subset>BG03</eFTI_subset>
            <eFTI_subset>BG04</eFTI_subset>
            <eFTI_subset>BG05</eFTI_subset>
            <eFTI_subset>BG06</eFTI_subset>
            <eFTI_subset>BG07</eFTI_subset>
            <eFTI_subset>BG08</eFTI_subset>
            <eFTI_subset>BG09</eFTI_subset>
            <eFTI_subset>BG10a</eFTI_subset>
            <eFTI_subset>BG10b</eFTI_subset>
            <eFTI_subset>CY01</eFTI_subset>
            <eFTI_subset>CY02</eFTI_subset>
            <eFTI_subset>CY03</eFTI_subset>
            <eFTI_subset>CZ01</eFTI_subset>
            <eFTI_subset>CZ02</eFTI_subset>
            <eFTI_subset>CZ03</eFTI_subset>
            <eFTI_subset>CZ04</eFTI_subset>
            <eFTI_subset>CZ05</eFTI_subset>
            <eFTI_subset>DE01</eFTI_subset>
            <eFTI_subset>DE02</eFTI_subset>
            <eFTI_subset>DE03a</eFTI_subset>
            <eFTI_subset>DE03b</eFTI_subset>
            <eFTI_subset>DE03c</eFTI_subset>
            <eFTI_subset>DE04</eFTI_subset>
            <eFTI_subset>DK01</eFTI_subset>
            <eFTI_subset>DK02</eFTI_subset>
            <eFTI_subset>DK03</eFTI_subset>
            <eFTI_subset>DK04</eFTI_subset>
            <eFTI_subset>DK05</eFTI_subset>
            <eFTI_subset>DK06</eFTI_subset>
            <eFTI_subset>EE01</eFTI_subset>
            <eFTI_subset>EE02</eFTI_subset>
            <eFTI_subset>EE04</eFTI_subset>
            <eFTI_subset>EE05a</eFTI_subset>
            <eFTI_subset>EE05b</eFTI_subset>
            <eFTI_subset>EE05c</eFTI_subset>
            <eFTI_subset>EE05d</eFTI_subset>
            <eFTI_subset>EL01</eFTI_subset>
            <eFTI_subset>EL02</eFTI_subset>
            <eFTI_subset>EL03</eFTI_subset>
            <eFTI_subset>EL04</eFTI_subset>
            <eFTI_subset>EL05</eFTI_subset>
            <eFTI_subset>EL07</eFTI_subset>
            <eFTI_subset>EL08</eFTI_subset>
            <eFTI_subset>ES01</eFTI_subset>
            <eFTI_subset>ES02</eFTI_subset>
            <eFTI_subset>ES03</eFTI_subset>
            <eFTI_subset>ES04</eFTI_subset>
            <eFTI_subset>ES05</eFTI_subset>
            <eFTI_subset>FI01</eFTI_subset>
            <eFTI_subset>FI02</eFTI_subset>
            <eFTI_subset>FI03</eFTI_subset>
            <eFTI_subset>FI04</eFTI_subset>
            <eFTI_subset>FR01a</eFTI_subset>
            <eFTI_subset>FR01b</eFTI_subset>
            <eFTI_subset>FR02a</eFTI_subset>
            <eFTI_subset>FR02b</eFTI_subset>
            <eFTI_subset>FR02c</eFTI_subset>
            <eFTI_subset>FR03</eFTI_subset>
            <eFTI_subset>FR04</eFTI_subset>
            <eFTI_subset>FR05</eFTI_subset>
            <eFTI_subset>HR01</eFTI_subset>
            <eFTI_subset>HR03</eFTI_subset>
            <eFTI_subset>HR04</eFTI_subset>
            <eFTI_subset>HR05a</eFTI_subset>
            <eFTI_subset>HR05b</eFTI_subset>
            <eFTI_subset>HR05c</eFTI_subset>
            <eFTI_subset>HU01</eFTI_subset>
            <eFTI_subset>HU02</eFTI_subset>
            <eFTI_subset>HU03</eFTI_subset>
            <eFTI_subset>HU04</eFTI_subset>
            <eFTI_subset>HU05</eFTI_subset>
            <eFTI_subset>HU06</eFTI_subset>
            <eFTI_subset>HU07</eFTI_subset>
            <eFTI_subset>IE01</eFTI_subset>
            <eFTI_subset>IE02</eFTI_subset>
            <eFTI_subset>IE03</eFTI_subset>
            <eFTI_subset>IE05</eFTI_subset>
            <eFTI_subset>IE06</eFTI_subset>
            <eFTI_subset>IE07</eFTI_subset>
            <eFTI_subset>IT01</eFTI_subset>
            <eFTI_subset>IT02</eFTI_subset>
            <eFTI_subset>IT03a</eFTI_subset>
            <eFTI_subset>IT03b</eFTI_subset>
            <eFTI_subset>IT03c</eFTI_subset>
            <eFTI_subset>LT01</eFTI_subset>
            <eFTI_subset>LT02</eFTI_subset>
            <eFTI_subset>LT03a</eFTI_subset>
            <eFTI_subset>LT03b</eFTI_subset>
            <eFTI_subset>LT04</eFTI_subset>
            <eFTI_subset>LT06</eFTI_subset>
            <eFTI_subset>LU01</eFTI_subset>
            <eFTI_subset>LU02</eFTI_subset>
            <eFTI_subset>LU03</eFTI_subset>
            <eFTI_subset>LU04</eFTI_subset>
            <eFTI_subset>LU05</eFTI_subset>
            <eFTI_subset>LU06</eFTI_subset>
            <eFTI_subset>LU07</eFTI_subset>
            <eFTI_subset>LV01</eFTI_subset>
            <eFTI_subset>LV02</eFTI_subset>
            <eFTI_subset>LV03</eFTI_subset>
            <eFTI_subset>LV04</eFTI_subset>
            <eFTI_subset>LV05</eFTI_subset>
            <eFTI_subset>MT01a</eFTI_subset>
            <eFTI_subset>MT01b</eFTI_subset>
            <eFTI_subset>MT02</eFTI_subset>
            <eFTI_subset>NL01</eFTI_subset>
            <eFTI_subset>NL02</eFTI_subset>
            <eFTI_subset>NL03a</eFTI_subset>
            <eFTI_subset>NL03b</eFTI_subset>
            <eFTI_subset>NL04</eFTI_subset>
            <eFTI_subset>NL05</eFTI_subset>
            <eFTI_subset>NL06</eFTI_subset>
            <eFTI_subset>PL01a</eFTI_subset>
            <eFTI_subset>PL01b</eFTI_subset>
            <eFTI_subset>PL01c</eFTI_subset>
            <eFTI_subset>PL02</eFTI_subset>
            <eFTI_subset>PL03</eFTI_subset>
            <eFTI_subset>PL04a</eFTI_subset>
            <eFTI_subset>PL04b</eFTI_subset>
            <eFTI_subset>PL04c</eFTI_subset>
            <eFTI_subset>PL06</eFTI_subset>
            <eFTI_subset>PT01</eFTI_subset>
            <eFTI_subset>PT02</eFTI_subset>
            <eFTI_subset>RO01</eFTI_subset>
            <eFTI_subset>RO02a</eFTI_subset>
            <eFTI_subset>RO02b</eFTI_subset>
            <eFTI_subset>RO03</eFTI_subset>
            <eFTI_subset>RO04</eFTI_subset>
            <eFTI_subset>RO05a</eFTI_subset>
            <eFTI_subset>RO05b</eFTI_subset>
            <eFTI_subset>RO05c</eFTI_subset>
            <eFTI_subset>RO06</eFTI_subset>
            <eFTI_subset>SE01</eFTI_subset>
            <eFTI_subset>SE02</eFTI_subset>
            <eFTI_subset>SE03</eFTI_subset>
            <eFTI_subset>SE04</eFTI_subset>
            <eFTI_subset>SE05</eFTI_subset>
            <eFTI_subset>SE06</eFTI_subset>
            <eFTI_subset>SI01</eFTI_subset>
            <eFTI_subset>SI02</eFTI_subset>
            <eFTI_subset>SI03</eFTI_subset>
            <eFTI_subset>SI05</eFTI_subset>
            <eFTI_subset>SI06</eFTI_subset>
            <eFTI_subset>SK01</eFTI_subset>
            <eFTI_subset>SK02</eFTI_subset>
            <eFTI_subset>SK03</eFTI_subset>
            <eFTI_subset>SK04</eFTI_subset>
            <eFTI_subset>SK05</eFTI_subset>
            <eFTI_xpath>/eFTIXM/ExchangedDocumentContext</eFTI_xpath>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ExchangedDocument" type="ram:ExchangedDocumentType">
        <xs:annotation>
          <xs:documentation>
            <eFTI_BN>eFTI Message Header</eFTI_BN>
            <eFTI_DEF>The eFTI data set header information.</eFTI_DEF>
            <eFTI_ID>ASBIE1859</eFTI_ID>
            <eFTI_subset>EU01</eFTI_subset>
            <eFTI_subset>EU02</eFTI_subset>
            <eFTI_subset>EU03</eFTI_subset>
            <eFTI_subset>EU05a</eFTI_subset>
            <eFTI_subset>EU05b</eFTI_subset>
            <eFTI_subset>EU05c</eFTI_subset>
            <eFTI_subset>EU06</eFTI_subset>
            <eFTI_subset>AT01</eFTI_subset>
            <eFTI_subset>AT02</eFTI_subset>
            <eFTI_subset>AT03</eFTI_subset>
            <eFTI_subset>AT04</eFTI_subset>
            <eFTI_subset>AT05</eFTI_subset>
            <eFTI_subset>AT06</eFTI_subset>
            <eFTI_subset>AT07</eFTI_subset>
            <eFTI_subset>AT08</eFTI_subset>
            <eFTI_subset>AT09</eFTI_subset>
            <eFTI_subset>AT11</eFTI_subset>
            <eFTI_subset>AT12</eFTI_subset>
            <eFTI_subset>AT13</eFTI_subset>
            <eFTI_subset>AT14</eFTI_subset>
            <eFTI_subset>AT15</eFTI_subset>
            <eFTI_subset>AT16</eFTI_subset>
            <eFTI_subset>BE01</eFTI_subset>
            <eFTI_subset>BE02</eFTI_subset>
            <eFTI_subset>BE03a</eFTI_subset>
            <eFTI_subset>BE03b</eFTI_subset>
            <eFTI_subset>BE04</eFTI_subset>
            <eFTI_subset>BE05</eFTI_subset>
            <eFTI_subset>BE06</eFTI_subset>
            <eFTI_subset>BE07</eFTI_subset>
            <eFTI_subset>BE08</eFTI_subset>
            <eFTI_subset>BE09</eFTI_subset>
            <eFTI_subset>BE10</eFTI_subset>
            <eFTI_subset>BG01</eFTI_subset>
            <eFTI_subset>BG02</eFTI_subset>
            <eFTI_subset>BG03</eFTI_subset>
            <eFTI_subset>BG04</eFTI_subset>
            <eFTI_subset>BG05</eFTI_subset>
            <eFTI_subset>BG06</eFTI_subset>
            <eFTI_subset>BG07</eFTI_subset>
            <eFTI_subset>BG08</eFTI_subset>
            <eFTI_subset>BG09</eFTI_subset>
            <eFTI_subset>BG10a</eFTI_subset>
            <eFTI_subset>BG10b</eFTI_subset>
            <eFTI_subset>CY01</eFTI_subset>
            <eFTI_subset>CY02</eFTI_subset>
            <eFTI_subset>CY03</eFTI_subset>
            <eFTI_subset>CZ01</eFTI_subset>
            <eFTI_subset>CZ02</eFTI_subset>
            <eFTI_subset>CZ03</eFTI_subset>
            <eFTI_subset>CZ04</eFTI_subset>
            <eFTI_subset>CZ05</eFTI_subset>
            <eFTI_subset>DE01</eFTI_subset>
            <eFTI_subset>DE02</eFTI_subset>
            <eFTI_subset>DE03a</eFTI_subset>
            <eFTI_subset>DE03b</eFTI_subset>
            <eFTI_subset>DE03c</eFTI_subset>
            <eFTI_subset>DE04</eFTI_subset>
            <eFTI_subset>DK01</eFTI_subset>
            <eFTI_subset>DK02</eFTI_subset>
            <eFTI_subset>DK03</eFTI_subset>
            <eFTI_subset>DK04</eFTI_subset>
            <eFTI_subset>DK05</eFTI_subset>
            <eFTI_subset>DK06</eFTI_subset>
            <eFTI_subset>EE01</eFTI_subset>
            <eFTI_subset>EE02</eFTI_subset>
            <eFTI_subset>EE04</eFTI_subset>
            <eFTI_subset>EE05a</eFTI_subset>
            <eFTI_subset>EE05b</eFTI_subset>
            <eFTI_subset>EE05c</eFTI_subset>
            <eFTI_subset>EE05d</eFTI_subset>
            <eFTI_subset>EL01</eFTI_subset>
            <eFTI_subset>EL02</eFTI_subset>
            <eFTI_subset>EL03</eFTI_subset>
            <eFTI_subset>EL04</eFTI_subset>
            <eFTI_subset>EL05</eFTI_subset>
            <eFTI_subset>EL07</eFTI_subset>
            <eFTI_subset>EL08</eFTI_subset>
            <eFTI_subset>ES01</eFTI_subset>
            <eFTI_subset>ES02</eFTI_subset>
            <eFTI_subset>ES03</eFTI_subset>
            <eFTI_subset>ES04</eFTI_subset>
            <eFTI_subset>ES05</eFTI_subset>
            <eFTI_subset>FI01</eFTI_subset>
            <eFTI_subset>FI02</eFTI_subset>
            <eFTI_subset>FI03</eFTI_subset>
            <eFTI_subset>FI04</eFTI_subset>
            <eFTI_subset>FR01a</eFTI_subset>
            <eFTI_subset>FR01b</eFTI_subset>
            <eFTI_subset>FR02a</eFTI_subset>
            <eFTI_subset>FR02b</eFTI_subset>
            <eFTI_subset>FR02c</eFTI_subset>
            <eFTI_subset>FR03</eFTI_subset>
            <eFTI_subset>FR04</eFTI_subset>
            <eFTI_subset>FR05</eFTI_subset>
            <eFTI_subset>HR01</eFTI_subset>
            <eFTI_subset>HR03</eFTI_subset>
            <eFTI_subset>HR04</eFTI_subset>
            <eFTI_subset>HR05a</eFTI_subset>
            <eFTI_subset>HR05b</eFTI_subset>
            <eFTI_subset>HR05c</eFTI_subset>
            <eFTI_subset>HU01</eFTI_subset>
            <eFTI_subset>HU02</eFTI_subset>
            <eFTI_subset>HU03</eFTI_subset>
            <eFTI_subset>HU04</eFTI_subset>
            <eFTI_subset>HU05</eFTI_subset>
            <eFTI_subset>HU06</eFTI_subset>
            <eFTI_subset>HU07</eFTI_subset>
            <eFTI_subset>IE01</eFTI_subset>
            <eFTI_subset>IE02</eFTI_subset>
            <eFTI_subset>IE03</eFTI_subset>
            <eFTI_subset>IE05</eFTI_subset>
            <eFTI_subset>IE06</eFTI_subset>
            <eFTI_subset>IE07</eFTI_subset>
            <eFTI_subset>IT01</eFTI_subset>
            <eFTI_subset>IT02</eFTI_subset>
            <eFTI_subset>IT03a</eFTI_subset>
            <eFTI_subset>IT03b</eFTI_subset>
            <eFTI_subset>IT03c</eFTI_subset>
            <eFTI_subset>LT01</eFTI_subset>
            <eFTI_subset>LT02</eFTI_subset>
            <eFTI_subset>LT03a</eFTI_subset>
            <eFTI_subset>LT03b</eFTI_subset>
            <eFTI_subset>LT04</eFTI_subset>
            <eFTI_subset>LT06</eFTI_subset>
            <eFTI_subset>LU01</eFTI_subset>
            <eFTI_subset>LU02</eFTI_subset>
            <eFTI_subset>LU03</eFTI_subset>
            <eFTI_subset>LU04</eFTI_subset>
            <eFTI_subset>LU05</eFTI_subset>
            <eFTI_subset>LU06</eFTI_subset>
            <eFTI_subset>LU07</eFTI_subset>
            <eFTI_subset>LV01</eFTI_subset>
            <eFTI_subset>LV02</eFTI_subset>
            <eFTI_subset>LV03</eFTI_subset>
            <eFTI_subset>LV04</eFTI_subset>
            <eFTI_subset>LV05</eFTI_subset>
            <eFTI_subset>MT01a</eFTI_subset>
            <eFTI_subset>MT01b</eFTI_subset>
            <eFTI_subset>MT02</eFTI_subset>
            <eFTI_subset>NL01</eFTI_subset>
            <eFTI_subset>NL02</eFTI_subset>
            <eFTI_subset>NL03a</eFTI_subset>
            <eFTI_subset>NL03b</eFTI_subset>
            <eFTI_subset>NL04</eFTI_subset>
            <eFTI_subset>NL05</eFTI_subset>
            <eFTI_subset>NL06</eFTI_subset>
            <eFTI_subset>PL01a</eFTI_subset>
            <eFTI_subset>PL01b</eFTI_subset>
            <eFTI_subset>PL01c</eFTI_subset>
            <eFTI_subset>PL02</eFTI_subset>
            <eFTI_subset>PL03</eFTI_subset>
            <eFTI_subset>PL04a</eFTI_subset>
            <eFTI_subset>PL04b</eFTI_subset>
            <eFTI_subset>PL04c</eFTI_subset>
            <eFTI_subset>PL06</eFTI_subset>
            <eFTI_subset>PT01</eFTI_subset>
            <eFTI_subset>PT02</eFTI_subset>
            <eFTI_subset>RO01</eFTI_subset>
            <eFTI_subset>RO02a</eFTI_subset>
            <eFTI_subset>RO02b</eFTI_subset>
            <eFTI_subset>RO03</eFTI_subset>
            <eFTI_subset>RO04</eFTI_subset>
            <eFTI_subset>RO05a</eFTI_subset>
            <eFTI_subset>RO05b</eFTI_subset>
            <eFTI_subset>RO05c</eFTI_subset>
            <eFTI_subset>RO06</eFTI_subset>
            <eFTI_subset>SE01</eFTI_subset>
            <eFTI_subset>SE02</eFTI_subset>
            <eFTI_subset>SE03</eFTI_subset>
            <eFTI_subset>SE04</eFTI_subset>
            <eFTI_subset>SE05</eFTI_subset>
            <eFTI_subset>SE06</eFTI_subset>
            <eFTI_subset>SI01</eFTI_subset>
            <eFTI_subset>SI02</eFTI_subset>
            <eFTI_subset>SI03</eFTI_subset>
            <eFTI_subset>SI05</eFTI_subset>
            <eFTI_subset>SI06</eFTI_subset>
            <eFTI_subset>SK01</eFTI_subset>
            <eFTI_subset>SK02</eFTI_subset>
            <eFTI_subset>SK03</eFTI_subset>
            <eFTI_subset>SK04</eFTI_subset>
            <eFTI_subset>SK05</eFTI_subset>
            <eFTI_xpath>/eFTIXM/ExchangedDocument</eFTI_xpath>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MessageInformation" type="ram:MessageInformationType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <eFTI_ID>ASBIE2135</eFTI_ID>
            <eFTI_DEF>Information pertaining to the operations associated with this message</eFTI_DEF>
            <eFTI_BN>eFTI Message Information</eFTI_BN>
            <eFTI_subset>EU01</eFTI_subset>
            <eFTI_subset>EU02</eFTI_subset>
            <eFTI_subset>EU03</eFTI_subset>
            <eFTI_subset>EU05a</eFTI_subset>
            <eFTI_subset>EU05b</eFTI_subset>
            <eFTI_subset>EU05c</eFTI_subset>
            <eFTI_subset>EU06</eFTI_subset>
            <eFTI_subset>AT01</eFTI_subset>
            <eFTI_subset>AT02</eFTI_subset>
            <eFTI_subset>AT03</eFTI_subset>
            <eFTI_subset>AT04</eFTI_subset>
            <eFTI_subset>AT05</eFTI_subset>
            <eFTI_subset>AT06</eFTI_subset>
            <eFTI_subset>AT07</eFTI_subset>
            <eFTI_subset>AT08</eFTI_subset>
            <eFTI_subset>AT09</eFTI_subset>
            <eFTI_subset>AT11</eFTI_subset>
            <eFTI_subset>AT12</eFTI_subset>
            <eFTI_subset>AT13</eFTI_subset>
            <eFTI_subset>AT14</eFTI_subset>
            <eFTI_subset>AT15</eFTI_subset>
            <eFTI_subset>AT16</eFTI_subset>
            <eFTI_subset>BE01</eFTI_subset>
            <eFTI_subset>BE02</eFTI_subset>
            <eFTI_subset>BE03a</eFTI_subset>
            <eFTI_subset>BE03b</eFTI_subset>
            <eFTI_subset>BE04</eFTI_subset>
            <eFTI_subset>BE05</eFTI_subset>
            <eFTI_subset>BE06</eFTI_subset>
            <eFTI_subset>BE07</eFTI_subset>
            <eFTI_subset>BE08</eFTI_subset>
            <eFTI_subset>BE09</eFTI_subset>
            <eFTI_subset>BE10</eFTI_subset>
            <eFTI_subset>BG01</eFTI_subset>
            <eFTI_subset>BG02</eFTI_subset>
            <eFTI_subset>BG03</eFTI_subset>
            <eFTI_subset>BG04</eFTI_subset>
            <eFTI_subset>BG05</eFTI_subset>
            <eFTI_subset>BG06</eFTI_subset>
            <eFTI_subset>BG07</eFTI_subset>
            <eFTI_subset>BG08</eFTI_subset>
            <eFTI_subset>BG09</eFTI_subset>
            <eFTI_subset>BG10a</eFTI_subset>
            <eFTI_subset>BG10b</eFTI_subset>
            <eFTI_subset>CY01</eFTI_subset>
            <eFTI_subset>CY02</eFTI_subset>
            <eFTI_subset>CY03</eFTI_subset>
            <eFTI_subset>CZ01</eFTI_subset>
            <eFTI_subset>CZ02</eFTI_subset>
            <eFTI_subset>CZ03</eFTI_subset>
            <eFTI_subset>CZ04</eFTI_subset>
            <eFTI_subset>CZ05</eFTI_subset>
            <eFTI_subset>DE01</eFTI_subset>
            <eFTI_subset>DE02</eFTI_subset>
            <eFTI_subset>DE03a</eFTI_subset>
            <eFTI_subset>DE03b</eFTI_subset>
            <eFTI_subset>DE03c</eFTI_subset>
            <eFTI_subset>DE04</eFTI_subset>
            <eFTI_subset>DK01</eFTI_subset>
            <eFTI_subset>DK02</eFTI_subset>
            <eFTI_subset>DK03</eFTI_subset>
            <eFTI_subset>DK04</eFTI_subset>
            <eFTI_subset>DK05</eFTI_subset>
            <eFTI_subset>DK06</eFTI_subset>
            <eFTI_subset>EE01</eFTI_subset>
            <eFTI_subset>EE02</eFTI_subset>
            <eFTI_subset>EE04</eFTI_subset>
            <eFTI_subset>EE05a</eFTI_subset>
            <eFTI_subset>EE05b</eFTI_subset>
            <eFTI_subset>EE05c</eFTI_subset>
            <eFTI_subset>EE05d</eFTI_subset>
            <eFTI_subset>EL01</eFTI_subset>
            <eFTI_subset>EL02</eFTI_subset>
            <eFTI_subset>EL03</eFTI_subset>
            <eFTI_subset>EL04</eFTI_subset>
            <eFTI_subset>EL05</eFTI_subset>
            <eFTI_subset>EL07</eFTI_subset>
            <eFTI_subset>EL08</eFTI_subset>
            <eFTI_subset>ES01</eFTI_subset>
            <eFTI_subset>ES02</eFTI_subset>
            <eFTI_subset>ES03</eFTI_subset>
            <eFTI_subset>ES04</eFTI_subset>
            <eFTI_subset>ES05</eFTI_subset>
            <eFTI_subset>FI01</eFTI_subset>
            <eFTI_subset>FI02</eFTI_subset>
            <eFTI_subset>FI03</eFTI_subset>
            <eFTI_subset>FI04</eFTI_subset>
            <eFTI_subset>FR01a</eFTI_subset>
            <eFTI_subset>FR01b</eFTI_subset>
            <eFTI_subset>FR02a</eFTI_subset>
            <eFTI_subset>FR02b</eFTI_subset>
            <eFTI_subset>FR02c</eFTI_subset>
            <eFTI_subset>FR03</eFTI_subset>
            <eFTI_subset>FR04</eFTI_subset>
            <eFTI_subset>FR05</eFTI_subset>
            <eFTI_subset>HR01</eFTI_subset>
            <eFTI_subset>HR03</eFTI_subset>
            <eFTI_subset>HR04</eFTI_subset>
            <eFTI_subset>HR05a</eFTI_subset>
            <eFTI_subset>HR05b</eFTI_subset>
            <eFTI_subset>HR05c</eFTI_subset>
            <eFTI_subset>HU01</eFTI_subset>
            <eFTI_subset>HU02</eFTI_subset>
            <eFTI_subset>HU03</eFTI_subset>
            <eFTI_subset>HU04</eFTI_subset>
            <eFTI_subset>HU05</eFTI_subset>
            <eFTI_subset>HU06</eFTI_subset>
            <eFTI_subset>HU07</eFTI_subset>
            <eFTI_subset>IE01</eFTI_subset>
            <eFTI_subset>IE02</eFTI_subset>
            <eFTI_subset>IE03</eFTI_subset>
            <eFTI_subset>IE05</eFTI_subset>
            <eFTI_subset>IE06</eFTI_subset>
            <eFTI_subset>IE07</eFTI_subset>
            <eFTI_subset>IT01</eFTI_subset>
            <eFTI_subset>IT02</eFTI_subset>
            <eFTI_subset>IT03a</eFTI_subset>
            <eFTI_subset>IT03b</eFTI_subset>
            <eFTI_subset>IT03c</eFTI_subset>
            <eFTI_subset>LT01</eFTI_subset>
            <eFTI_subset>LT02</eFTI_subset>
            <eFTI_subset>LT03a</eFTI_subset>
            <eFTI_subset>LT03b</eFTI_subset>
            <eFTI_subset>LT04</eFTI_subset>
            <eFTI_subset>LT06</eFTI_subset>
            <eFTI_subset>LU01</eFTI_subset>
            <eFTI_subset>LU02</eFTI_subset>
            <eFTI_subset>LU03</eFTI_subset>
            <eFTI_subset>LU04</eFTI_subset>
            <eFTI_subset>LU05</eFTI_subset>
            <eFTI_subset>LU06</eFTI_subset>
            <eFTI_subset>LU07</eFTI_subset>
            <eFTI_subset>LV01</eFTI_subset>
            <eFTI_subset>LV02</eFTI_subset>
            <eFTI_subset>LV03</eFTI_subset>
            <eFTI_subset>LV04</eFTI_subset>
            <eFTI_subset>LV05</eFTI_subset>
            <eFTI_subset>MT01a</eFTI_subset>
            <eFTI_subset>MT01b</eFTI_subset>
            <eFTI_subset>MT02</eFTI_subset>
            <eFTI_subset>NL01</eFTI_subset>
            <eFTI_subset>NL02</eFTI_subset>
            <eFTI_subset>NL03a</eFTI_subset>
            <eFTI_subset>NL03b</eFTI_subset>
            <eFTI_subset>NL04</eFTI_subset>
            <eFTI_subset>NL05</eFTI_subset>
            <eFTI_subset>NL06</eFTI_subset>
            <eFTI_subset>PL01a</eFTI_subset>
            <eFTI_subset>PL01b</eFTI_subset>
            <eFTI_subset>PL01c</eFTI_subset>
            <eFTI_subset>PL02</eFTI_subset>
            <eFTI_subset>PL03</eFTI_subset>
            <eFTI_subset>PL04a</eFTI_subset>
            <eFTI_subset>PL04b</eFTI_subset>
            <eFTI_subset>PL04c</eFTI_subset>
            <eFTI_subset>PL06</eFTI_subset>
            <eFTI_subset>PT01</eFTI_subset>
            <eFTI_subset>PT02</eFTI_subset>
            <eFTI_subset>RO01</eFTI_subset>
            <eFTI_subset>RO02a</eFTI_subset>
            <eFTI_subset>RO02b</eFTI_subset>
            <eFTI_subset>RO03</eFTI_subset>
            <eFTI_subset>RO04</eFTI_subset>
            <eFTI_subset>RO05a</eFTI_subset>
            <eFTI_subset>RO05b</eFTI_subset>
            <eFTI_subset>RO05c</eFTI_subset>
            <eFTI_subset>RO06</eFTI_subset>
            <eFTI_subset>SE01</eFTI_subset>
            <eFTI_subset>SE02</eFTI_subset>
            <eFTI_subset>SE03</eFTI_subset>
            <eFTI_subset>SE04</eFTI_subset>
            <eFTI_subset>SE05</eFTI_subset>
            <eFTI_subset>SE06</eFTI_subset>
            <eFTI_subset>SI01</eFTI_subset>
            <eFTI_subset>SI02</eFTI_subset>
            <eFTI_subset>SI03</eFTI_subset>
            <eFTI_subset>SI05</eFTI_subset>
            <eFTI_subset>SI06</eFTI_subset>
            <eFTI_subset>SK01</eFTI_subset>
            <eFTI_subset>SK02</eFTI_subset>
            <eFTI_subset>SK03</eFTI_subset>
            <eFTI_subset>SK04</eFTI_subset>
            <eFTI_subset>SK05</eFTI_subset>
            <eFTI_xpath>/eFTIXM/MessageInformation</eFTI_xpath>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="EFTIIDInformation" type="ram:EFTIIDInformationType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <eFTI_ID>ASBIE2008</eFTI_ID>
            <eFTI_DEF>eFTI related identifiers and related search parameters.</eFTI_DEF>
            <eFTI_BN>eFTI Identifiers</eFTI_BN>
            <eFTI_subset>EU01</eFTI_subset>
            <eFTI_subset>EU02</eFTI_subset>
            <eFTI_subset>EU03</eFTI_subset>
            <eFTI_subset>EU05a</eFTI_subset>
            <eFTI_subset>EU05b</eFTI_subset>
            <eFTI_subset>EU05c</eFTI_subset>
            <eFTI_subset>EU06</eFTI_subset>
            <eFTI_subset>AT01</eFTI_subset>
            <eFTI_subset>AT02</eFTI_subset>
            <eFTI_subset>AT03</eFTI_subset>
            <eFTI_subset>AT04</eFTI_subset>
            <eFTI_subset>AT05</eFTI_subset>
            <eFTI_subset>AT06</eFTI_subset>
            <eFTI_subset>AT07</eFTI_subset>
            <eFTI_subset>AT08</eFTI_subset>
            <eFTI_subset>AT09</eFTI_subset>
            <eFTI_subset>AT11</eFTI_subset>
            <eFTI_subset>AT12</eFTI_subset>
            <eFTI_subset>AT13</eFTI_subset>
            <eFTI_subset>AT14</eFTI_subset>
            <eFTI_subset>AT15</eFTI_subset>
            <eFTI_subset>AT16</eFTI_subset>
            <eFTI_subset>BE01</eFTI_subset>
            <eFTI_subset>BE02</eFTI_subset>
            <eFTI_subset>BE03a</eFTI_subset>
            <eFTI_subset>BE03b</eFTI_subset>
            <eFTI_subset>BE04</eFTI_subset>
            <eFTI_subset>BE05</eFTI_subset>
            <eFTI_subset>BE06</eFTI_subset>
            <eFTI_subset>BE07</eFTI_subset>
            <eFTI_subset>BE08</eFTI_subset>
            <eFTI_subset>BE09</eFTI_subset>
            <eFTI_subset>BE10</eFTI_subset>
            <eFTI_subset>BG01</eFTI_subset>
            <eFTI_subset>BG02</eFTI_subset>
            <eFTI_subset>BG03</eFTI_subset>
            <eFTI_subset>BG04</eFTI_subset>
            <eFTI_subset>BG05</eFTI_subset>
            <eFTI_subset>BG06</eFTI_subset>
            <eFTI_subset>BG07</eFTI_subset>
            <eFTI_subset>BG08</eFTI_subset>
            <eFTI_subset>BG09</eFTI_subset>
            <eFTI_subset>BG10a</eFTI_subset>
            <eFTI_subset>BG10b</eFTI_subset>
            <eFTI_subset>CY01</eFTI_subset>
            <eFTI_subset>CY02</eFTI_subset>
            <eFTI_subset>CY03</eFTI_subset>
            <eFTI_subset>CZ01</eFTI_subset>
            <eFTI_subset>CZ02</eFTI_subset>
            <eFTI_subset>CZ03</eFTI_subset>
            <eFTI_subset>CZ04</eFTI_subset>
            <eFTI_subset>CZ05</eFTI_subset>
            <eFTI_subset>DE01</eFTI_subset>
            <eFTI_subset>DE02</eFTI_subset>
            <eFTI_subset>DE03a</eFTI_subset>
            <eFTI_subset>DE03b</eFTI_subset>
            <eFTI_subset>DE03c</eFTI_subset>
            <eFTI_subset>DE04</eFTI_subset>
            <eFTI_subset>DK01</eFTI_subset>
            <eFTI_subset>DK02</eFTI_subset>
            <eFTI_subset>DK03</eFTI_subset>
            <eFTI_subset>DK04</eFTI_subset>
            <eFTI_subset>DK05</eFTI_subset>
            <eFTI_subset>DK06</eFTI_subset>
            <eFTI_subset>EE01</eFTI_subset>
            <eFTI_subset>EE02</eFTI_subset>
            <eFTI_subset>EE04</eFTI_subset>
            <eFTI_subset>EE05a</eFTI_subset>
            <eFTI_subset>EE05b</eFTI_subset>
            <eFTI_subset>EE05c</eFTI_subset>
            <eFTI_subset>EE05d</eFTI_subset>
            <eFTI_subset>EL01</eFTI_subset>
            <eFTI_subset>EL02</eFTI_subset>
            <eFTI_subset>EL03</eFTI_subset>
            <eFTI_subset>EL04</eFTI_subset>
            <eFTI_subset>EL05</eFTI_subset>
            <eFTI_subset>EL07</eFTI_subset>
            <eFTI_subset>EL08</eFTI_subset>
            <eFTI_subset>ES01</eFTI_subset>
            <eFTI_subset>ES02</eFTI_subset>
            <eFTI_subset>ES03</eFTI_subset>
            <eFTI_subset>ES04</eFTI_subset>
            <eFTI_subset>ES05</eFTI_subset>
            <eFTI_subset>FI01</eFTI_subset>
            <eFTI_subset>FI02</eFTI_subset>
            <eFTI_subset>FI03</eFTI_subset>
            <eFTI_subset>FI04</eFTI_subset>
            <eFTI_subset>FR01a</eFTI_subset>
            <eFTI_subset>FR01b</eFTI_subset>
            <eFTI_subset>FR02a</eFTI_subset>
            <eFTI_subset>FR02b</eFTI_subset>
            <eFTI_subset>FR02c</eFTI_subset>
            <eFTI_subset>FR03</eFTI_subset>
            <eFTI_subset>FR04</eFTI_subset>
            <eFTI_subset>FR05</eFTI_subset>
            <eFTI_subset>HR01</eFTI_subset>
            <eFTI_subset>HR03</eFTI_subset>
            <eFTI_subset>HR04</eFTI_subset>
            <eFTI_subset>HR05a</eFTI_subset>
            <eFTI_subset>HR05b</eFTI_subset>
            <eFTI_subset>HR05c</eFTI_subset>
            <eFTI_subset>HU01</eFTI_subset>
            <eFTI_subset>HU02</eFTI_subset>
            <eFTI_subset>HU03</eFTI_subset>
            <eFTI_subset>HU04</eFTI_subset>
            <eFTI_subset>HU05</eFTI_subset>
            <eFTI_subset>HU06</eFTI_subset>
            <eFTI_subset>HU07</eFTI_subset>
            <eFTI_subset>IE01</eFTI_subset>
            <eFTI_subset>IE02</eFTI_subset>
            <eFTI_subset>IE03</eFTI_subset>
            <eFTI_subset>IE05</eFTI_subset>
            <eFTI_subset>IE06</eFTI_subset>
            <eFTI_subset>IE07</eFTI_subset>
            <eFTI_subset>IT01</eFTI_subset>
            <eFTI_subset>IT02</eFTI_subset>
            <eFTI_subset>IT03a</eFTI_subset>
            <eFTI_subset>IT03b</eFTI_subset>
            <eFTI_subset>IT03c</eFTI_subset>
            <eFTI_subset>LT01</eFTI_subset>
            <eFTI_subset>LT02</eFTI_subset>
            <eFTI_subset>LT03a</eFTI_subset>
            <eFTI_subset>LT03b</eFTI_subset>
            <eFTI_subset>LT04</eFTI_subset>
            <eFTI_subset>LT06</eFTI_subset>
            <eFTI_subset>LU01</eFTI_subset>
            <eFTI_subset>LU02</eFTI_subset>
            <eFTI_subset>LU03</eFTI_subset>
            <eFTI_subset>LU04</eFTI_subset>
            <eFTI_subset>LU05</eFTI_subset>
            <eFTI_subset>LU06</eFTI_subset>
            <eFTI_subset>LU07</eFTI_subset>
            <eFTI_subset>LV01</eFTI_subset>
            <eFTI_subset>LV02</eFTI_subset>
            <eFTI_subset>LV03</eFTI_subset>
            <eFTI_subset>LV04</eFTI_subset>
            <eFTI_subset>LV05</eFTI_subset>
            <eFTI_subset>MT01a</eFTI_subset>
            <eFTI_subset>MT01b</eFTI_subset>
            <eFTI_subset>MT02</eFTI_subset>
            <eFTI_subset>NL01</eFTI_subset>
            <eFTI_subset>NL02</eFTI_subset>
            <eFTI_subset>NL03a</eFTI_subset>
            <eFTI_subset>NL03b</eFTI_subset>
            <eFTI_subset>NL04</eFTI_subset>
            <eFTI_subset>NL05</eFTI_subset>
            <eFTI_subset>NL06</eFTI_subset>
            <eFTI_subset>PL01a</eFTI_subset>
            <eFTI_subset>PL01b</eFTI_subset>
            <eFTI_subset>PL01c</eFTI_subset>
            <eFTI_subset>PL02</eFTI_subset>
            <eFTI_subset>PL03</eFTI_subset>
            <eFTI_subset>PL04a</eFTI_subset>
            <eFTI_subset>PL04b</eFTI_subset>
            <eFTI_subset>PL04c</eFTI_subset>
            <eFTI_subset>PL06</eFTI_subset>
            <eFTI_subset>PT01</eFTI_subset>
            <eFTI_subset>PT02</eFTI_subset>
            <eFTI_subset>RO01</eFTI_subset>
            <eFTI_subset>RO02a</eFTI_subset>
            <eFTI_subset>RO02b</eFTI_subset>
            <eFTI_subset>RO03</eFTI_subset>
            <eFTI_subset>RO04</eFTI_subset>
            <eFTI_subset>RO05a</eFTI_subset>
            <eFTI_subset>RO05b</eFTI_subset>
            <eFTI_subset>RO05c</eFTI_subset>
            <eFTI_subset>RO06</eFTI_subset>
            <eFTI_subset>SE01</eFTI_subset>
            <eFTI_subset>SE02</eFTI_subset>
            <eFTI_subset>SE03</eFTI_subset>
            <eFTI_subset>SE04</eFTI_subset>
            <eFTI_subset>SE05</eFTI_subset>
            <eFTI_subset>SE06</eFTI_subset>
            <eFTI_subset>SI01</eFTI_subset>
            <eFTI_subset>SI02</eFTI_subset>
            <eFTI_subset>SI03</eFTI_subset>
            <eFTI_subset>SI05</eFTI_subset>
            <eFTI_subset>SI06</eFTI_subset>
            <eFTI_subset>SK01</eFTI_subset>
            <eFTI_subset>SK02</eFTI_subset>
            <eFTI_subset>SK03</eFTI_subset>
            <eFTI_subset>SK04</eFTI_subset>
            <eFTI_subset>SK05</eFTI_subset>
            <eFTI_xpath>/eFTIXM/EFTIIDInformation</eFTI_xpath>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SpecifiedSupplyChainConsignment" type="ram:SupplyChainConsignmentType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            <eFTI_DEF>The consignment is a separately identifiable collection of consignment Items (available to be) transported from only one consignor to only one consignee via one or more modes of transport. A consignment can be at a master level which covers a consolidated cargo (could be a single house level consignment or more than one) contracted between freight forwarder as the consignor and a carrier, or at house level which covers the cargo contracted to be moved by the freight forwarder on behalf of the buyer or the seller. In addition in case of road, it can also be at a subcontract level which covers the case of a road carrier (aka. haulier) contracted to move the goods on behalf of another road carrier.</eFTI_DEF>
            <eFTI_BN>eFTI data set consignment</eFTI_BN>
            <eFTI_ID>ASBIE1027</eFTI_ID>
            <eFTI_subset>EU01</eFTI_subset>
            <eFTI_subset>EU02</eFTI_subset>
            <eFTI_subset>EU03</eFTI_subset>
            <eFTI_subset>EU05a</eFTI_subset>
            <eFTI_subset>EU05b</eFTI_subset>
            <eFTI_subset>EU05c</eFTI_subset>
            <eFTI_subset>EU06</eFTI_subset>
            <eFTI_subset>AT01</eFTI_subset>
            <eFTI_subset>AT02</eFTI_subset>
            <eFTI_subset>AT03</eFTI_subset>
            <eFTI_subset>AT04</eFTI_subset>
            <eFTI_subset>AT05</eFTI_subset>
            <eFTI_subset>AT06</eFTI_subset>
            <eFTI_subset>AT07</eFTI_subset>
            <eFTI_subset>AT08</eFTI_subset>
            <eFTI_subset>AT09</eFTI_subset>
            <eFTI_subset>AT11</eFTI_subset>
            <eFTI_subset>AT12</eFTI_subset>
            <eFTI_subset>AT13</eFTI_subset>
            <eFTI_subset>AT14</eFTI_subset>
            <eFTI_subset>AT15</eFTI_subset>
            <eFTI_subset>AT16</eFTI_subset>
            <eFTI_subset>BE01</eFTI_subset>
            <eFTI_subset>BE02</eFTI_subset>
            <eFTI_subset>BE03a</eFTI_subset>
            <eFTI_subset>BE03b</eFTI_subset>
            <eFTI_subset>BE04</eFTI_subset>
            <eFTI_subset>BE05</eFTI_subset>
            <eFTI_subset>BE06</eFTI_subset>
            <eFTI_subset>BE07</eFTI_subset>
            <eFTI_subset>BE08</eFTI_subset>
            <eFTI_subset>BE09</eFTI_subset>
            <eFTI_subset>BE10</eFTI_subset>
            <eFTI_subset>BG01</eFTI_subset>
            <eFTI_subset>BG02</eFTI_subset>
            <eFTI_subset>BG03</eFTI_subset>
            <eFTI_subset>BG04</eFTI_subset>
            <eFTI_subset>BG05</eFTI_subset>
            <eFTI_subset>BG06</eFTI_subset>
            <eFTI_subset>BG07</eFTI_subset>
            <eFTI_subset>BG08</eFTI_subset>
            <eFTI_subset>BG09</eFTI_subset>
            <eFTI_subset>BG10a</eFTI_subset>
            <eFTI_subset>BG10b</eFTI_subset>
            <eFTI_subset>CY01</eFTI_subset>
            <eFTI_subset>CY02</eFTI_subset>
            <eFTI_subset>CY03</eFTI_subset>
            <eFTI_subset>CZ01</eFTI_subset>
            <eFTI_subset>CZ02</eFTI_subset>
            <eFTI_subset>CZ03</eFTI_subset>
            <eFTI_subset>CZ04</eFTI_subset>
            <eFTI_subset>CZ05</eFTI_subset>
            <eFTI_subset>DE01</eFTI_subset>
            <eFTI_subset>DE02</eFTI_subset>
            <eFTI_subset>DE03a</eFTI_subset>
            <eFTI_subset>DE03b</eFTI_subset>
            <eFTI_subset>DE03c</eFTI_subset>
            <eFTI_subset>DE04</eFTI_subset>
            <eFTI_subset>DK01</eFTI_subset>
            <eFTI_subset>DK02</eFTI_subset>
            <eFTI_subset>DK03</eFTI_subset>
            <eFTI_subset>DK04</eFTI_subset>
            <eFTI_subset>DK05</eFTI_subset>
            <eFTI_subset>DK06</eFTI_subset>
            <eFTI_subset>EE01</eFTI_subset>
            <eFTI_subset>EE02</eFTI_subset>
            <eFTI_subset>EE04</eFTI_subset>
            <eFTI_subset>EE05a</eFTI_subset>
            <eFTI_subset>EE05b</eFTI_subset>
            <eFTI_subset>EE05c</eFTI_subset>
            <eFTI_subset>EE05d</eFTI_subset>
            <eFTI_subset>EL01</eFTI_subset>
            <eFTI_subset>EL02</eFTI_subset>
            <eFTI_subset>EL03</eFTI_subset>
            <eFTI_subset>EL04</eFTI_subset>
            <eFTI_subset>EL05</eFTI_subset>
            <eFTI_subset>EL07</eFTI_subset>
            <eFTI_subset>EL08</eFTI_subset>
            <eFTI_subset>ES01</eFTI_subset>
            <eFTI_subset>ES02</eFTI_subset>
            <eFTI_subset>ES03</eFTI_subset>
            <eFTI_subset>ES04</eFTI_subset>
            <eFTI_subset>ES05</eFTI_subset>
            <eFTI_subset>FI01</eFTI_subset>
            <eFTI_subset>FI02</eFTI_subset>
            <eFTI_subset>FI03</eFTI_subset>
            <eFTI_subset>FI04</eFTI_subset>
            <eFTI_subset>FR01a</eFTI_subset>
            <eFTI_subset>FR01b</eFTI_subset>
            <eFTI_subset>FR02a</eFTI_subset>
            <eFTI_subset>FR02b</eFTI_subset>
            <eFTI_subset>FR02c</eFTI_subset>
            <eFTI_subset>FR03</eFTI_subset>
            <eFTI_subset>FR04</eFTI_subset>
            <eFTI_subset>FR05</eFTI_subset>
            <eFTI_subset>HR01</eFTI_subset>
            <eFTI_subset>HR03</eFTI_subset>
            <eFTI_subset>HR04</eFTI_subset>
            <eFTI_subset>HR05a</eFTI_subset>
            <eFTI_subset>HR05b</eFTI_subset>
            <eFTI_subset>HR05c</eFTI_subset>
            <eFTI_subset>HU01</eFTI_subset>
            <eFTI_subset>HU02</eFTI_subset>
            <eFTI_subset>HU03</eFTI_subset>
            <eFTI_subset>HU04</eFTI_subset>
            <eFTI_subset>HU05</eFTI_subset>
            <eFTI_subset>HU06</eFTI_subset>
            <eFTI_subset>HU07</eFTI_subset>
            <eFTI_subset>IE01</eFTI_subset>
            <eFTI_subset>IE02</eFTI_subset>
            <eFTI_subset>IE03</eFTI_subset>
            <eFTI_subset>IE05</eFTI_subset>
            <eFTI_subset>IE06</eFTI_subset>
            <eFTI_subset>IE07</eFTI_subset>
            <eFTI_subset>IT01</eFTI_subset>
            <eFTI_subset>IT02</eFTI_subset>
            <eFTI_subset>IT03a</eFTI_subset>
            <eFTI_subset>IT03b</eFTI_subset>
            <eFTI_subset>IT03c</eFTI_subset>
            <eFTI_subset>LT01</eFTI_subset>
            <eFTI_subset>LT02</eFTI_subset>
            <eFTI_subset>LT03a</eFTI_subset>
            <eFTI_subset>LT03b</eFTI_subset>
            <eFTI_subset>LT04</eFTI_subset>
            <eFTI_subset>LT06</eFTI_subset>
            <eFTI_subset>LU01</eFTI_subset>
            <eFTI_subset>LU02</eFTI_subset>
            <eFTI_subset>LU03</eFTI_subset>
            <eFTI_subset>LU04</eFTI_subset>
            <eFTI_subset>LU05</eFTI_subset>
            <eFTI_subset>LU06</eFTI_subset>
            <eFTI_subset>LU07</eFTI_subset>
            <eFTI_subset>LV01</eFTI_subset>
            <eFTI_subset>LV02</eFTI_subset>
            <eFTI_subset>LV03</eFTI_subset>
            <eFTI_subset>LV04</eFTI_subset>
            <eFTI_subset>LV05</eFTI_subset>
            <eFTI_subset>MT01a</eFTI_subset>
            <eFTI_subset>MT01b</eFTI_subset>
            <eFTI_subset>MT02</eFTI_subset>
            <eFTI_subset>NL01</eFTI_subset>
            <eFTI_subset>NL02</eFTI_subset>
            <eFTI_subset>NL03a</eFTI_subset>
            <eFTI_subset>NL03b</eFTI_subset>
            <eFTI_subset>NL04</eFTI_subset>
            <eFTI_subset>NL05</eFTI_subset>
            <eFTI_subset>NL06</eFTI_subset>
            <eFTI_subset>PL01a</eFTI_subset>
            <eFTI_subset>PL01b</eFTI_subset>
            <eFTI_subset>PL01c</eFTI_subset>
            <eFTI_subset>PL02</eFTI_subset>
            <eFTI_subset>PL03</eFTI_subset>
            <eFTI_subset>PL04a</eFTI_subset>
            <eFTI_subset>PL04b</eFTI_subset>
            <eFTI_subset>PL04c</eFTI_subset>
            <eFTI_subset>PL06</eFTI_subset>
            <eFTI_subset>PT01</eFTI_subset>
            <eFTI_subset>PT02</eFTI_subset>
            <eFTI_subset>RO01</eFTI_subset>
            <eFTI_subset>RO02a</eFTI_subset>
            <eFTI_subset>RO02b</eFTI_subset>
            <eFTI_subset>RO03</eFTI_subset>
            <eFTI_subset>RO04</eFTI_subset>
            <eFTI_subset>RO05a</eFTI_subset>
            <eFTI_subset>RO05b</eFTI_subset>
            <eFTI_subset>RO05c</eFTI_subset>
            <eFTI_subset>RO06</eFTI_subset>
            <eFTI_subset>SE01</eFTI_subset>
            <eFTI_subset>SE02</eFTI_subset>
            <eFTI_subset>SE03</eFTI_subset>
            <eFTI_subset>SE04</eFTI_subset>
            <eFTI_subset>SE05</eFTI_subset>
            <eFTI_subset>SE06</eFTI_subset>
            <eFTI_subset>SI01</eFTI_subset>
            <eFTI_subset>SI02</eFTI_subset>
            <eFTI_subset>SI03</eFTI_subset>
            <eFTI_subset>SI05</eFTI_subset>
            <eFTI_subset>SI06</eFTI_subset>
            <eFTI_subset>SK01</eFTI_subset>
            <eFTI_subset>SK02</eFTI_subset>
            <eFTI_subset>SK03</eFTI_subset>
            <eFTI_subset>SK04</eFTI_subset>
            <eFTI_subset>SK05</eFTI_subset>
            <eFTI_xpath>/eFTIXM/SpecifiedSupplyChainConsignment</eFTI_xpath>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
