<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:qdt="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
           elementFormDefault="qualified"
           version="34.0">
  <xs:import namespace="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34" schemaLocation="FTI019s_urn_eu_move_eFTI_data_standard_UnqualifiedDataType_34.xsd"/>
  <xs:simpleType name="CountryIDContentType">
    <xs:restriction base="xs:token">
      <xs:enumeration value="AD"/>
      <xs:enumeration value="AE"/>
      <xs:enumeration value="AF"/>
      <xs:enumeration value="AG"/>
      <xs:enumeration value="AI"/>
      <xs:enumeration value="AL"/>
      <xs:enumeration value="AM"/>
      <xs:enumeration value="AO"/>
      <xs:enumeration value="AQ"/>
      <xs:enumeration value="AR"/>
      <xs:enumeration value="AS"/>
      <xs:enumeration value="AT"/>
      <xs:enumeration value="AU"/>
      <xs:enumeration value="AW"/>
      <xs:enumeration value="AX"/>
      <xs:enumeration value="AZ"/>
      <xs:enumeration value="BA"/>
      <xs:enumeration value="BB"/>
      <xs:enumeration value="BD"/>
      <xs:enumeration value="BE"/>
      <xs:enumeration value="BF"/>
      <xs:enumeration value="BG"/>
      <xs:enumeration value="BH"/>
      <xs:enumeration value="BI"/>
      <xs:enumeration value="BJ"/>
      <xs:enumeration value="BL"/>
      <xs:enumeration value="BM"/>
      <xs:enumeration value="BN"/>
      <xs:enumeration value="BO"/>
      <xs:enumeration value="BQ"/>
      <xs:enumeration value="BR"/>
      <xs:enumeration value="BS"/>
      <xs:enumeration value="BT"/>
      <xs:enumeration value="BV"/>
      <xs:enumeration value="BW"/>
      <xs:enumeration value="BY"/>
      <xs:enumeration value="BZ"/>
      <xs:enumeration value="CA"/>
      <xs:enumeration value="CC"/>
      <xs:enumeration value="CD"/>
      <xs:enumeration value="CF"/>
      <xs:enumeration value="CG"/>
      <xs:enumeration value="CH"/>
      <xs:enumeration value="CI"/>
      <xs:enumeration value="CK"/>
      <xs:enumeration value="CL"/>
      <xs:enumeration value="CM"/>
      <xs:enumeration value="CN"/>
      <xs:enumeration value="CO"/>
      <xs:enumeration value="CR"/>
      <xs:enumeration value="CU"/>
      <xs:enumeration value="CV"/>
      <xs:enumeration value="CW"/>
      <xs:enumeration value="CX"/>
      <xs:enumeration value="CY"/>
      <xs:enumeration value="CZ"/>
      <xs:enumeration value="DE"/>
      <xs:enumeration value="DJ"/>
      <xs:enumeration value="DK"/>
      <xs:enumeration value="DM"/>
      <xs:enumeration value="DO"/>
      <xs:enumeration value="DZ"/>
      <xs:enumeration value="EC"/>
      <xs:enumeration value="EE"/>
      <xs:enumeration value="EG"/>
      <xs:enumeration value="EH"/>
      <xs:enumeration value="ER"/>
      <xs:enumeration value="ES"/>
      <xs:enumeration value="ET"/>
      <xs:enumeration value="FI"/>
      <xs:enumeration value="FJ"/>
      <xs:enumeration value="FK"/>
      <xs:enumeration value="FM"/>
      <xs:enumeration value="FO"/>
      <xs:enumeration value="FR"/>
      <xs:enumeration value="GA"/>
      <xs:enumeration value="GB"/>
      <xs:enumeration value="GD"/>
      <xs:enumeration value="GE"/>
      <xs:enumeration value="GF"/>
      <xs:enumeration value="GG"/>
      <xs:enumeration value="GH"/>
      <xs:enumeration value="GI"/>
      <xs:enumeration value="GL"/>
      <xs:enumeration value="GM"/>
      <xs:enumeration value="GN"/>
      <xs:enumeration value="GP"/>
      <xs:enumeration value="GQ"/>
      <xs:enumeration value="GR"/>
      <xs:enumeration value="GS"/>
      <xs:enumeration value="GT"/>
      <xs:enumeration value="GU"/>
      <xs:enumeration value="GW"/>
      <xs:enumeration value="GY"/>
      <xs:enumeration value="HK"/>
      <xs:enumeration value="HM"/>
      <xs:enumeration value="HN"/>
      <xs:enumeration value="HR"/>
      <xs:enumeration value="HT"/>
      <xs:enumeration value="HU"/>
      <xs:enumeration value="ID"/>
      <xs:enumeration value="IE"/>
      <xs:enumeration value="IL"/>
      <xs:enumeration value="IM"/>
      <xs:enumeration value="IN"/>
      <xs:enumeration value="IO"/>
      <xs:enumeration value="IQ"/>
      <xs:enumeration value="IR"/>
      <xs:enumeration value="IS"/>
      <xs:enumeration value="IT"/>
      <xs:enumeration value="JE"/>
      <xs:enumeration value="JM"/>
      <xs:enumeration value="JO"/>
      <xs:enumeration value="JP"/>
      <xs:enumeration value="KE"/>
      <xs:enumeration value="KG"/>
      <xs:enumeration value="KH"/>
      <xs:enumeration value="KI"/>
      <xs:enumeration value="KM"/>
      <xs:enumeration value="KN"/>
      <xs:enumeration value="KP"/>
      <xs:enumeration value="KR"/>
      <xs:enumeration value="KW"/>
      <xs:enumeration value="KY"/>
      <xs:enumeration value="KZ"/>
      <xs:enumeration value="LA"/>
      <xs:enumeration value="LB"/>
      <xs:enumeration value="LC"/>
      <xs:enumeration value="LI"/>
      <xs:enumeration value="LK"/>
      <xs:enumeration value="LR"/>
      <xs:enumeration value="LS"/>
      <xs:enumeration value="LT"/>
      <xs:enumeration value="LU"/>
      <xs:enumeration value="LV"/>
      <xs:enumeration value="LY"/>
      <xs:enumeration value="MA"/>
      <xs:enumeration value="MC"/>
      <xs:enumeration value="MD"/>
      <xs:enumeration value="ME"/>
      <xs:enumeration value="MF"/>
      <xs:enumeration value="MG"/>
      <xs:enumeration value="MH"/>
      <xs:enumeration value="MK"/>
      <xs:enumeration value="ML"/>
      <xs:enumeration value="MM"/>
      <xs:enumeration value="MN"/>
      <xs:enumeration value="MO"/>
      <xs:enumeration value="MP"/>
      <xs:enumeration value="MQ"/>
      <xs:enumeration value="MR"/>
      <xs:enumeration value="MS"/>
      <xs:enumeration value="MT"/>
      <xs:enumeration value="MU"/>
      <xs:enumeration value="MV"/>
      <xs:enumeration value="MW"/>
      <xs:enumeration value="MX"/>
      <xs:enumeration value="MY"/>
      <xs:enumeration value="MZ"/>
      <xs:enumeration value="NA"/>
      <xs:enumeration value="NC"/>
      <xs:enumeration value="NE"/>
      <xs:enumeration value="NF"/>
      <xs:enumeration value="NG"/>
      <xs:enumeration value="NI"/>
      <xs:enumeration value="NL"/>
      <xs:enumeration value="NO"/>
      <xs:enumeration value="NP"/>
      <xs:enumeration value="NR"/>
      <xs:enumeration value="NU"/>
      <xs:enumeration value="NZ"/>
      <xs:enumeration value="OM"/>
      <xs:enumeration value="PA"/>
      <xs:enumeration value="PE"/>
      <xs:enumeration value="PF"/>
      <xs:enumeration value="PG"/>
      <xs:enumeration value="PH"/>
      <xs:enumeration value="PK"/>
      <xs:enumeration value="PL"/>
      <xs:enumeration value="PM"/>
      <xs:enumeration value="PN"/>
      <xs:enumeration value="PR"/>
      <xs:enumeration value="PS"/>
      <xs:enumeration value="PT"/>
      <xs:enumeration value="PW"/>
      <xs:enumeration value="PY"/>
      <xs:enumeration value="QA"/>
      <xs:enumeration value="RE"/>
      <xs:enumeration value="RO"/>
      <xs:enumeration value="RS"/>
      <xs:enumeration value="RU"/>
      <xs:enumeration value="RW"/>
      <xs:enumeration value="SA"/>
      <xs:enumeration value="SB"/>
      <xs:enumeration value="SC"/>
      <xs:enumeration value="SD"/>
      <xs:enumeration value="SE"/>
      <xs:enumeration value="SG"/>
      <xs:enumeration value="SH"/>
      <xs:enumeration value="SI"/>
      <xs:enumeration value="SJ"/>
      <xs:enumeration value="SK"/>
      <xs:enumeration value="SL"/>
      <xs:enumeration value="SM"/>
      <xs:enumeration value="SN"/>
      <xs:enumeration value="SO"/>
      <xs:enumeration value="SR"/>
      <xs:enumeration value="SS"/>
      <xs:enumeration value="ST"/>
      <xs:enumeration value="SV"/>
      <xs:enumeration value="SX"/>
      <xs:enumeration value="SY"/>
      <xs:enumeration value="SZ"/>
      <xs:enumeration value="TC"/>
      <xs:enumeration value="TD"/>
      <xs:enumeration value="TF"/>
      <xs:enumeration value="TG"/>
      <xs:enumeration value="TH"/>
      <xs:enumeration value="TJ"/>
      <xs:enumeration value="TK"/>
      <xs:enumeration value="TL"/>
      <xs:enumeration value="TM"/>
      <xs:enumeration value="TN"/>
      <xs:enumeration value="TO"/>
      <xs:enumeration value="TR"/>
      <xs:enumeration value="TT"/>
      <xs:enumeration value="TV"/>
      <xs:enumeration value="TW"/>
      <xs:enumeration value="TZ"/>
      <xs:enumeration value="UA"/>
      <xs:enumeration value="UG"/>
      <xs:enumeration value="UM"/>
      <xs:enumeration value="US"/>
      <xs:enumeration value="UY"/>
      <xs:enumeration value="UZ"/>
      <xs:enumeration value="VA"/>
      <xs:enumeration value="VC"/>
      <xs:enumeration value="VE"/>
      <xs:enumeration value="VG"/>
      <xs:enumeration value="VI"/>
      <xs:enumeration value="VN"/>
      <xs:enumeration value="VU"/>
      <xs:enumeration value="WF"/>
      <xs:enumeration value="WS"/>
      <xs:enumeration value="YE"/>
      <xs:enumeration value="YT"/>
      <xs:enumeration value="ZA"/>
      <xs:enumeration value="ZM"/>
      <xs:enumeration value="ZW"/>
      <xs:length value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CountryIDType">
    <xs:simpleContent>
      <xs:extension base="qdt:CountryIDContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DocumentCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:token"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="token">
    <xs:restriction base="xs:token">
      <xs:enumeration value="019"/>
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TransportEquipmentCategoryCodeContentType">
    <xs:restriction base="xs:token">
      <xs:enumeration value="AE"/>
      <xs:enumeration value="BR"/>
      <xs:enumeration value="BX"/>
      <xs:enumeration value="DPL"/>
      <xs:enumeration value="RF"/>
      <xs:enumeration value="RR"/>
      <xs:enumeration value="SM"/>
      <xs:enumeration value="T1"/>
      <xs:enumeration value="T10"/>
      <xs:enumeration value="T14"/>
      <xs:enumeration value="T5"/>
      <xs:enumeration value="T9"/>
      <xs:enumeration value="TE"/>
      <xs:enumeration value="TN"/>
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TransportEquipmentCategoryCodeContentType_2">
    <xs:restriction base="xs:token">
      <xs:enumeration value="AM"/>
      <xs:enumeration value="BPO"/>
      <xs:enumeration value="BPP"/>
      <xs:enumeration value="BPQ"/>
      <xs:enumeration value="BPR"/>
      <xs:enumeration value="BPX"/>
      <xs:enumeration value="CN"/>
      <xs:enumeration value="SW"/>
      <xs:enumeration value="T11"/>
      <xs:enumeration value="T12"/>
      <xs:enumeration value="T13"/>
      <xs:enumeration value="T2"/>
      <xs:enumeration value="T3"/>
      <xs:enumeration value="T4"/>
      <xs:enumeration value="T6"/>
      <xs:enumeration value="T7"/>
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="TransportEquipmentCategoryCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportEquipmentCategoryCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TransportEquipmentCategoryCodeType_2">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportEquipmentCategoryCodeContentType_2"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="TransportMeansTypeCodeContentType">
    <xs:restriction base="xs:token">
      <xs:enumeration value="1501"/>
      <xs:enumeration value="1502"/>
      <xs:enumeration value="1503"/>
      <xs:enumeration value="1504"/>
      <xs:enumeration value="1505"/>
      <xs:enumeration value="1506"/>
      <xs:enumeration value="1511"/>
      <xs:enumeration value="1512"/>
      <xs:enumeration value="1513"/>
      <xs:enumeration value="1514"/>
      <xs:enumeration value="1515"/>
      <xs:enumeration value="1516"/>
      <xs:enumeration value="1517"/>
      <xs:enumeration value="1518"/>
      <xs:enumeration value="1519"/>
      <xs:enumeration value="1521"/>
      <xs:enumeration value="1522"/>
      <xs:enumeration value="1523"/>
      <xs:enumeration value="1524"/>
      <xs:enumeration value="1525"/>
      <xs:enumeration value="1531"/>
      <xs:enumeration value="1532"/>
      <xs:enumeration value="1533"/>
      <xs:enumeration value="1534"/>
      <xs:enumeration value="1541"/>
      <xs:enumeration value="1542"/>
      <xs:enumeration value="1543"/>
      <xs:enumeration value="1551"/>
      <xs:enumeration value="1552"/>
      <xs:enumeration value="1553"/>
      <xs:enumeration value="1591"/>
      <xs:enumeration value="1592"/>
      <xs:enumeration value="1593"/>
      <xs:enumeration value="1594"/>
      <xs:enumeration value="1601"/>
      <xs:enumeration value="1602"/>
      <xs:enumeration value="1603"/>
      <xs:enumeration value="1604"/>
      <xs:enumeration value="1605"/>
      <xs:enumeration value="1606"/>
      <xs:enumeration value="1607"/>
      <xs:enumeration value="1711"/>
      <xs:enumeration value="1712"/>
      <xs:enumeration value="1721"/>
      <xs:enumeration value="1723"/>
      <xs:enumeration value="1724"/>
      <xs:enumeration value="1725"/>
      <xs:enumeration value="1726"/>
      <xs:enumeration value="1727"/>
      <xs:enumeration value="1728"/>
      <xs:enumeration value="1729"/>
      <xs:enumeration value="1751"/>
      <xs:enumeration value="1752"/>
      <xs:enumeration value="1753"/>
      <xs:enumeration value="1761"/>
      <xs:enumeration value="1762"/>
      <xs:enumeration value="1763"/>
      <xs:enumeration value="1764"/>
      <xs:enumeration value="1765"/>
      <xs:enumeration value="1766"/>
      <xs:enumeration value="1781"/>
      <xs:enumeration value="1782"/>
      <xs:enumeration value="2201"/>
      <xs:enumeration value="2202"/>
      <xs:enumeration value="2203"/>
      <xs:enumeration value="2301"/>
      <xs:enumeration value="2302"/>
      <xs:enumeration value="2303"/>
      <xs:enumeration value="2304"/>
      <xs:enumeration value="2305"/>
      <xs:enumeration value="3100"/>
      <xs:enumeration value="3101"/>
      <xs:enumeration value="3102"/>
      <xs:enumeration value="3103"/>
      <xs:enumeration value="3104"/>
      <xs:enumeration value="3105"/>
      <xs:enumeration value="3106"/>
      <xs:enumeration value="3107"/>
      <xs:enumeration value="3108"/>
      <xs:enumeration value="3109"/>
      <xs:enumeration value="3110"/>
      <xs:enumeration value="3111"/>
      <xs:enumeration value="3112"/>
      <xs:enumeration value="3113"/>
      <xs:enumeration value="3114"/>
      <xs:enumeration value="3115"/>
      <xs:enumeration value="3116"/>
      <xs:enumeration value="3117"/>
      <xs:enumeration value="3118"/>
      <xs:enumeration value="3119"/>
      <xs:enumeration value="3120"/>
      <xs:enumeration value="3121"/>
      <xs:enumeration value="3122"/>
      <xs:enumeration value="3123"/>
      <xs:enumeration value="3124"/>
      <xs:enumeration value="3125"/>
      <xs:enumeration value="3126"/>
      <xs:enumeration value="3127"/>
      <xs:enumeration value="3128"/>
      <xs:enumeration value="3129"/>
      <xs:enumeration value="3130"/>
      <xs:enumeration value="3131"/>
      <xs:enumeration value="3132"/>
      <xs:enumeration value="3133"/>
      <xs:enumeration value="3134"/>
      <xs:enumeration value="3135"/>
      <xs:enumeration value="3136"/>
      <xs:enumeration value="3137"/>
      <xs:enumeration value="3138"/>
      <xs:enumeration value="3201"/>
      <xs:enumeration value="3301"/>
      <xs:enumeration value="3302"/>
      <xs:enumeration value="3303"/>
      <xs:enumeration value="3304"/>
      <xs:enumeration value="4000"/>
      <xs:enumeration value="5000"/>
      <xs:enumeration value="8021"/>
      <xs:enumeration value="8022"/>
      <xs:enumeration value="8023"/>
      <xs:enumeration value="8161"/>
      <xs:enumeration value="8162"/>
      <xs:enumeration value="8163"/>
      <xs:enumeration value="8441"/>
      <xs:enumeration value="8442"/>
      <xs:enumeration value="8443"/>
      <xs:enumeration value="8444"/>
      <xs:enumeration value="8445"/>
      <xs:enumeration value="8446"/>
      <xs:enumeration value="8447"/>
      <xs:enumeration value="8448"/>
      <xs:enumeration value="8451"/>
      <xs:enumeration value="8452"/>
      <xs:enumeration value="8453"/>
      <xs:enumeration value="8454"/>
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="TransportMeansTypeCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportMeansTypeCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="TransportModeCodeContentType">
    <xs:restriction base="xs:token">
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
      <xs:enumeration value="4"/>
      <xs:enumeration value="8"/>
      <xs:length value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="TransportModeCodeType">
    <xs:simpleContent>
      <xs:extension base="qdt:TransportModeCodeContentType"/>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>
