<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:qdt="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:eu:move:eFTI:data:standard:QualifiedDataType:34"
           elementFormDefault="qualified"
           version="34.0">
  <xs:import namespace="urn:eu:move:eFTI:data:standard:UnqualifiedDataType:34" schemaLocation="FTI030n_urn_eu_move_eFTI_data_standard_UnqualifiedDataType_34.xsd"/>
  <xs:simpleType name="CountryIDContentType">
    <xs:restriction base="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="CountryIDType">
    <xs:simpleContent>
      <xs:extension base="qdt:CountryIDContentType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DocumentCodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DocumentStatusCodeType">
    <xs:simpleContent>
      <xs:extension base="xs:token"/>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>
